### ISSUE TITLE
Feature Request: missing whitelisted hostnames option for subfolders with nginx

### ISSUE THREAD

**Issue by jakobhviid** [linuxserver/docker-transmission#101]
Going to mynginxpage.url/transmission gets me to the webpage when forwarded. Instead, I get an error that the domain name is not whitelisted.

There should be an option to set whitelisted networks and hostnames in the docker configuration.

**Comment by drizuid** [comment]
PRs are accepted, though I don't think we are planning to add more envvars; you can easily whitelist in the settings.json
