### ISSUE TITLE
Is the EXPOSE directive really needed in the Dockerfile?

### ISSUE THREAD

**Issue by brasse** [linuxserver/docker-transmission#103]
Don't know if this the right channel for this, but here goes. Is the EXPOSE directive really needed in the Docker file? I.e. `EXPOSE 9091 51413`. We need to expose ports when we do `docker create` anyway. When configuring the transmission daemon i wanted to use another peer port and exposed that port like this `-p 26433:26433` when doing `docker create`. Isn't the EXPOSE directive in the Dockerfile redundant and a bit wrong?

**Comment by aptalca** [comment]
Redundant, maybe, but wrong, it is not.

The expose is mainly for documentation purposes and is used by some docker management apps
