### ISSUE TITLE
uPNP port mapping not working

### ISSUE THREAD

**Issue by sentience** [linuxserver/docker-transmission#105]
Transmission and other applications running on my local network (including on the Docker host) are able successfully to set up port mapping on my router. For some reason, uPNP port mapping for Transmission in this Docker container doesn't work.

------------------------------

## Expected Behavior
Transmission should map its port (51413) on my router via uPNP.

## Current Behavior
The port is not mapped. The relevant log output is:

```
[2020-04-28 19:50:31.675] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70)
[2020-04-28 19:50:31.675] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70)
[2020-04-28 19:50:39.673] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:90)
[2020-04-28 19:50:40.673] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:90)
```

## Steps to Reproduce
1. Ensure uPNP is enabled on your router.
2. Verify that Transmission running in a desktop OS (such as macOS) is able successfully to set up its port with uPNP.
3. Launch this Docker container with default settings.

## Environment
**OS:** Synology DSM 6.2.2-24922 Update 5
**CPU architecture:** INTEL Celeron J3455
**How docker service was installed:** Synology Package Center

## Command used to create docker container (run/create/compose/screenshot)

```
docker create \
  --name=linuxserver-transmission1 \
  -e PUID=1028 \
  -e PGID=100 \
  -e TZ=Australia/Melbourne \
  -e TRANSMISSION_WEB_HOME=/combustion-release/ \
  -e USER=admin \
  -e PASS=admin \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v /volume1/NAS/Transmission/config:/config \
  -v /volume1/NAS/Transmission/downloads:/downloads \
  -v /volume1/NAS/Transmission/watch:/watch \
  linuxserver/transmission
```

## Docker logs
[docker-transmission.log](https://github.com/linuxserver/docker-transmission/files/4544921/docker-transmission.log)

**Comment by tobbenb** [comment]
You probably need to map the correct ports for upnp for it to work.

**Comment by sentience** [comment]
I found the issue and its solution [described in the README](https://github.com/dgholz/docker-transmission/#i-set-portmap-true-in-config-but-the-port-is-still-closed-what-gives) of another Transmission Docker container:

># I set `portmap: true` in config but the port is still closed! What gives?
>
>Transmission sends out a NAT-PMP (uPNP) packet to your router, asking it to forward connection to some port back to the same port at the address Tranmission is running on. Docker created a private internal network for your container, and NATs the traffic through the host Docker is running on. Docker doesn't understand the uPNP packet, and isn't allowed to forward it, so it gets dropped.
>
>Solutions:
>
>1. use `--net=host` so Docker does not set up NATting of the traffic from the container
>2. statically forward port 51413 TCP & UDP to the docker host from your router
>3. teach Docker how to handle uPNP (hard)

Would you be happy to add similar instructions to the README of this repo?

**Comment by CHBMB** [comment]
I'm against this, upnp isn't something I think we should advocate and something I'd always suggest switching off on the router/firewall.

 Far better and more secure to leave any port opening to be done manually/consciously by the user.

**Comment by drizuid** [comment]
upnp is not designed to work this way because it is a multicast protocol and works on its own subnet. This isn't something you should expect to work nor is it something we can make work

**Comment by tubbo** [comment]
note for anyone reading this, setting transmission to use host networking mode is what will make it work with upnp. similar approach that the plex container takes. not sure if this can be done without host networking mode on though...it might need to know where the router is and such in order to set ports on it.
