### ISSUE TITLE
2.94 tag updated to Transmission 3.0

### ISSUE THREAD

**Issue by dagingaa** [linuxserver/docker-transmission#114]
## Expected Behavior
When installing 2.94-r3-ls54 I expect Transmission 2.94 to be installed

## Current Behavior
When installing 2.94-r3-ls54 Transmission 3 is installed

## Steps to Reproduce
1. `docker pull linuxserver/transmission:2.94-r3-ls54`
2. Verify that Transmission 3 is installed, or just look at https://github.com/linuxserver/docker-transmission/commit/725889ca099d057106f24d6f3bb1ea9b01113324 which was added in https://github.com/linuxserver/docker-transmission/pull/113

I would expect this to update the tag to linuxserver/transmission:3.0-ls1, as we have a new major version installed now. Currently there is no way to ensure that you get future updates to 2.94 should your torrent site demand it, you need to install `2.94-r3-ls53`

Unfortunately those of us using Portainer to keep packages up to date are now no longer able to downgrade without manually rehashing and fixing all seeded torrents as there is no downgrade path for Transmission 3.0 -> 2.94.

**Comment by aptalca** [comment]
Thanks, updating.

**Comment by aptalca** [comment]
@dagingaa apologies for that. We totally missed that the version tag was repo dependent. We're fixing it on our end. Sorry for the trouble.

**Comment by aptalca** [comment]
For anyone else tracking this, the images are now properly tagged 3.0 and the previous erroneously tagged images are removed from docker hub
