### ISSUE TITLE
New UI theme - Shift

### ISSUE THREAD

**Issue by achembarpu** [linuxserver/docker-transmission#118]
Hi!

I found a pretty neat, well-maintained transmission web ui called "[Shift](https://github.com/killemov/Shift)". Would it be possible to integrate this?

Thanks!

**Comment by bagobones** [comment]
I believe most of the alternate WEB based UIs work by replacing files in the main transmission web directory. Might be nice to have generalized support to point to an alternate UI in the config folder or something?
