### ISSUE TITLE
Labels feature

### ISSUE THREAD

**Issue by linareyne** [linuxserver/docker-transmission#121]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
Labels would be cool

## Current Behavior
No labels

## Steps to Reproduce
This guy's labels feature got merged into a dev branch
https://github.com/transmission-remote-gui/transgui/issues/978

Any chance this could be incorporated into the container at some point?

**Comment by qu1ck** [comment]
Issue you linked is about GUI support for labels in transmission-remote-gui project. Label support is in transmission server since 3.0 release so you already have it.

**Comment by drizuid** [comment]
We do not modify the application. You can make a dockermods to accomplish this i guess: https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
