### ISSUE TITLE
Add combustion dark theme?

### ISSUE THREAD

**Issue by linareyne** [linuxserver/docker-transmission#122]
Would be great to have a dark theme option. Looks like the only difference in the repo below is a single css file.

Available here: https://github.com/SebDanielsson/dark-combustion

**Comment by drizuid** [comment]
you can do this if you follow
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
Not all users will want that theme so there's no reason for us to force them to have it loaded, as it's a user choice, we provide easy customization of our containers.
