### ISSUE TITLE
How to use with docker uid/gid and a Synology NAS Server with NFS volume? Permission issue

### ISSUE THREAD

**Issue by kopax** [linuxserver/docker-transmission#126]
## Expected Behavior

I expect the server to start properly with a Synology NFS mounted drive

## Current Behavior

I keep having permissions issues on startup while changing owner ship.

The permisssions for `/downloads` directory is owned by uid 1034, while I setup the uid with `PUID`.

On my synology NAS volume setting, I use squash mapping `Map root to admin` and I don't know if it's the correct squash settings for docker-transmission.

All other settings fail on my host to mount nfs with access denied

It also work if I use squash settings `no mappings`, I can star the container with the proper file permissions on the system, but then I get:

```
[2020-09-21 22:59:33.313] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
```

## Steps to Reproduce

1. Create a volume on a Synology NAS server
1. Activate nfs on the NAS
1. Configure squash for no mappings or rount to  admin
1. Fix file permission on the NAS volume to be uid/gid 1000/1000
1. Start docker-transmissions as the README.md docker-compose.yml example
1. Watch logs
1. Notice  `[2020-09-21 23:00:11.370] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)`

## Environment
**OS:**      Debian Buster Linux 5.7 bpo
**CPU architecture:** x64
**How docker service was installed:**      

Official linuxserver/docker-transmission docker hub image according to documentation

## Command used to create docker container (run/create/compose/screenshot)

Exactly as in the README.md

## Docker logs

This is the relevant part:

```bash
Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

chown: changing ownership of '/config': Operation not permitted
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
chown: changing ownership of '/config/settings.json': Operation not permitted
chown: changing ownership of '/downloads': Operation not permitted
chown: changing ownership of '/downloads/complete': Operation not permitted
chown: changing ownership of '/downloads/incomplete': Operation not permitted
chown: changing ownership of '/watch': Operation not permitted

```

**Comment by kopax** [comment]
Thank you @github-actions bot but I tried to click on your issue template link and it's broken, perhaps an human can help?

**Comment by kopax** [comment]
I finally managed using the `No mapping` squash settings and a chown on the nas for the directory to get the container starting with the proper permissions.

But now i have this:

```bash
[2020-09-21 23:18:05.421] transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-3.00/daemon/daemon.c:825)
```

I have tried to create `/config/settings.json` in various way with various settings and I keep having that error.

It seems that this image doesn't work out of the box, or am I missing something?

**Comment by j0nnymoe** [comment]
You need to look at your permissions for the folder you're using to map to `/config`. We don't recommend/support using remote mounts for the `/config` mounts as they don't place nicely (as you're currently experiencing).
This container works fine when using a folder on the local filesystem.

**Comment by kopax** [comment]
Thanks, solved the issue.

I wanted to use transmissions with flexget, also from linuxserver, I wonder how the 3 jellyfin transmission and flexget can share the Download directory, do they need some extra configuration to get setup? (https://flexget.com/Cookbook/Transmission), thanks for any advices.

**Comment by j0nnymoe** [comment]
Glad that solved it.
