### ISSUE TITLE
Please upgrade transmission-web-control to 1.6.1

### ISSUE THREAD

**Issue by LarkinZero** [linuxserver/docker-transmission#128]
## Expected Behavior

Transmission-web-control has released v1.6.1.
https://github.com/ronggang/transmission-web-control/releases
## Current Behavior

current version is v1.6.0-beta2
## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**

**Comment by wiserain** [comment]
It is already there. Pull and upgrade your container.
