### ISSUE TITLE
New version of GUI Transmission-Web-Control (20200913 -> v1.6.1)

### ISSUE THREAD

**Issue by zilexa** [linuxserver/docker-transmission#130]
Just an fyi if it can be included in the next image update as I don't think we can install the newer version ourselves.

**Comment by j0nnymoe** [comment]
https://github.com/linuxserver/docker-transmission/issues/128

**Comment by zilexa** [comment]
It is actually possible to update manually. Via Portainer > Containers > Transmission > Open Console. 
Then run these two commands described here: https://github.com/ronggang/transmission-web-control/wiki/Linux-Installation#install-transmission-web-control

You may have to clear browser cache.

**Comment by j0nnymoe** [comment]
When this container has a new image built, it pulls the latest version : https://github.com/linuxserver/docker-transmission/blob/master/Dockerfile#L41 as per the docker file here.
