### ISSUE TITLE
Latest docker-transmission build is broken with NordVPN

### ISSUE THREAD

**Issue by roysubs** [linuxserver/docker-transmission#137]
## Expected Behavior
docker-transmission should use NordVPN as the VPN.

## Current Behavior
NordVPN says that it cannot logon. I know this is wrong because I use NordVPN on 2 systems as my main VPN and all works perfectly with my login credentials.

## Steps to Reproduce

1. Use NordVPN
2. Try to use docker-transmission with NordVPN

## Environment
CentOS 8
x86_64
Really bare / clean system, CentOS 8 Minimal, git, ansible, docker from official docker repo

I don't think much is required, it just doesn't work with NordVPN, but please let me know specific files to send and I'll do that (i.e. what is the filesystem location of the files that you want me to send?).

**Comment by CHBMB** [comment]
Well, our container doesn't have inherent VPN support, so my first thought is are you using another author's container?

**Comment by roysubs** [comment]
> Well, our container doesn't have inherent VPN support, so my first thought is are you using another author's container?

My bad, I've been following some notes from a friend and wrongly conflated that with this package then..
