### ISSUE TITLE
Something gets wrong in DSM7.0

### ISSUE THREAD

**Issue by skypjsfly** [linuxserver/docker-transmission#138]
I find it that when transmission runs in docker,and the system is synology DSM7.0. When I set Memory limit(cache limit),and the use of cache reach the limit,The system calls that The system is running out of memory. #
![QQ截图20201202203857](https://user-images.githubusercontent.com/32484309/100873704-85605880-34de-11eb-9795-4e86d98f3fb0.jpg)
Any container memory exceeds the limit,the system warns.So,I want to ask you how can I set a Memory limit(cache limit) through the environment variable.Maybe only by this way can I limit the use of transmission.

OS: synology DSM7.0
CPU architecture: x86_64

My English is very poor. I can only say this way.

**Comment by w4o** [comment]
I'am also getting this problem on DSM 7.0.
@skypjsfly  请问找到解决方法了吗？

**Comment by thelamer** [comment]
If you have memory usage problems with this container the only recommendation I can make is to try an alternative program. 
We wrap applications in docker and try to automate setup and usage for general consumption. Where possible we can make tweaks to default settings to make more sense in Docker. In this case I do not see what we can do to "fix" this issue.
