### ISSUE TITLE
Blocklists

### ISSUE THREAD

**Issue by snowwing** [linuxserver/docker-transmission#14]
See: https://github.com/transmission/transmission/wiki/Blocklists

It's generally good practice to run transmission with blocklists so I think it would be a good idea to setup a default blocklist in the settings.json (probably http://list.iblocklist.com/?list=bt_level1&fileformat=p2p&archiveformat=gz) and enable it.

We'd then need to set it up to regularly update the blocklist by installing transmission-remote and setting up a daily cron job to run:
transmission-remote -n admin:password --blocklist-update

I would submit this as a pull request but I am not sure how to setup the cron job in docker.

**Comment by sparklyballs** [comment]
Blocklists can be enabled via the webui by clicking the spanner/wrench and navigating to :- 

![screen shot 2016-10-16 at 13 14 43](https://cloud.githubusercontent.com/assets/4343808/19417362/a5fb6936-93a2-11e6-83b0-8ab4a3746161.png)

**Comment by snowwing** [comment]
Yes, but that's the problem. It's a manual update. So you have to remember to update it regularly. If you set up the cron job then you don't have to worry about it.

But maybe this should be running in a separate docker container?

**Comment by sparklyballs** [comment]
the issue with a cron job is user/password for people who have secured their webui as per instructions in our [readme](https://github.com/linuxserver/docker-transmission#securing-the-webui-with-a-usernamepassword).

**Comment by snowwing** [comment]
Could that be passed in as a parameter -e UIADMIN= -e UIPASS= ?

**Comment by phendryx** [comment]
I have a feature branch that is mostly complete for this. The update script is smart enough to look at the settings.json file, for the `blocklist-enabled` variable to be set to true and optionally uses authentication if `rpc-authentication-required` is set to true, using 2 environment variables set in the docker configuration. It will be run once a day.

PR should be submitted tomorrow sometime.

**Comment by sparklyballs** [comment]
i really dislike passing in usernames and passwords through environment variables and try to avoid it all costs.
All it takes is `docker inspect <container-name>` and it will show the credentials in plain text.

**Comment by phendryx** [comment]
Only other options I see is maybe a file in the /config directory that would contain the username and password. Would that be better?

**Comment by snowwing** [comment]
Genuine question as I am not sure of the security implications, but if someone can run docker inspect on the host don't you have bigger problems then them discovering the password?

**Comment by sparklyballs** [comment]
from the outside world yes, but not all threats are external.

**Comment by phendryx** [comment]
@sparklyballs found a different way to update the block list, http://blog.shvetsov.com/2010/09/automatically-update-transmission-block.html. So we borrowed the idea. The update script now downloads the url that is stored in the settings.json file, decompresses it, puts it in the right directory and restarts the transmission daemon. No need for authentication or passing cleartext passwords.

**Comment by snowwing** [comment]
Thank you @sparklyballs and @phendryx
