### ISSUE TITLE
Alpine 3.13 broken on 32bit systems

### ISSUE THREAD

**Issue by Alkanov** [linuxserver/docker-transmission#147]
Hey guys, alpine 3.13 is broken in 32 bit systems (aka rasp pis)

Not even `docker run --rm alpine:3.13 apk add git` would run, and the latest transmission is broken because of this.

**Comment by aptalca** [comment]
see the container log

**Comment by Alkanov** [comment]
Logs will look fine, but when you issue the `date` command you can see the date is not right.

This issue was spotted in gluetun while debugging alpine 3.13; ultimately a rollback to 3.12 fixed all issues on 32-bit ARM

https://github.com/qdm12/gluetun/issues/360#issuecomment-770309823

**Comment by aptalca** [comment]
See here: https://docs.linuxserver.io/faq#libseccomp

Our baseimage logs a message with that link if your host is affected

**Comment by Alkanov** [comment]
My bad, I see you guys have it all there - you can close this issue then
