### ISSUE TITLE
403: Forbidden when trying to access the WebGUI

### ISSUE THREAD

**Issue by gertvdv** [linuxserver/docker-transmission#151]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
I have installed docker-transmission on a server in my local network (192.168.1.5). 

When connecting from my pc (192.168.1.120), I get:

403: Forbidden
Unauthorized IP Address.
Either disable the IP address whitelist or add your address to it.
If you're editing settings.json, see the 'rpc-whitelist' and 'rpc-whitelist-enabled' entries.
If you're still using ACLs, use a whitelist instead. See the transmission-daemon manpage for details.

## Current Behavior
While I understand changes in the settings.json should be made through the environment variables, there is none environment variable for "rpc-whitelist": "127.0.0.1,::1",

When trying to change it manually to:
"rpc-whitelist": "192.168.1.120,127.0.0.1,::1",

The deamon overwrites it to the above defaults when starting the container.

## Environment
**OS: Ubuntu 20.04

**Comment by LC1207** [comment]
how did you fix this?
