### ISSUE TITLE
transmission.log missing from /config dir

### ISSUE THREAD

**Issue by elisimpson** [linuxserver/docker-transmission#155]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
On a typical transmission install a transmission.log file is created in the /config dir

## Current Behavior
transmission.log is missing from config dir. config.json, stats.json, and dht.dat are created correctly as expected.

## Steps to Reproduce
1. Go to mounted /config dir
2. check for transmission.log... isn't there
3. ???
4. profit

## Environment
Synology NAS 6.2.4
x86_64

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --name transmission -e PUID=1000 -e PGID=1000 -e USER=user -e PASS=pass -v /volume1/docker/transmission:/config -p 9091:9091 -p 51413:51413 -p 51413:51413/udp --restart unless-stopped ghcr.io/linuxserver/transmission

Note: the UIDs and USER/PASS above are placeholder values
Note 2: I initially thought stats.json was also not being created but I was mistaken. transmission.log is still an issue though.

## Docker logs
N/A

**Comment by iruahn** [comment]
Where is transmission.log file??
/config dir doesn't have log file.

**Comment by iruahn** [comment]
Is this matter being analyzed?

**Comment by seelenamt** [comment]
I'm having this problem too. I was hoping I could use it to figure out what issue I'm having with whitelisting a different container, but without the transmission.log file I'm not sure how to progress.

**Comment by Iolaum** [comment]
I am also not seeing any logs in the `config` dir.

**Comment by moreje** [comment]
I also need this logs  for debugging RPC acces attempts... but nothing available..

**Comment by elisimpson** [comment]
Any progress on this?

**Comment by Iolaum** [comment]
Could it be that the log file is what you would see if you type `docker logs transmission` and that's the intended way to access them?

**Comment by iatacs19** [comment]
Any updates?

**Comment by teror4uks** [comment]
Any updates?

**Comment by teror4uks** [comment]
@iatacs19  as dirty workaround you could add into `run` script `--log-debug --logfile /config/transmission.log` option.

```
vi /var/run/s6/services/transmission/run
```

here (highlighted):
![image](https://user-images.githubusercontent.com/10071749/150697795-8f80ba1f-cb82-4e32-b70f-bb24aedf7114.png)

then kill transmission process

```
ps aux | grep transmission-daemon
kill <pid transmission-daemon>
```

the s6-supervisor will restart daemon with new parameters and you could find log file into /config dir

**Comment by thelamer** [comment]
This docker container runs Transmission in the foreground and logs to the docker console. We don't have plans to pipe that to a file or enable debug logging.

**Comment by wally-crunk** [comment]
> the s6-supervisor will restart daemon with new parameters and you could find log file into /config dir

Thank you for the heroic reply.

**Comment by fiore42** [comment]
The amazing tip from @teror4uks doesn't seem to work anymore, so I've updated it to automate it a bit and with the right file location for my system 

write this script in the /config folder in your host (I named it start_logging.sh ):

```
#! /bin/bash

if [[ -f /run/s6-rc/servicedirs/svc-transmission/run && -z "$(awk '/\/usr\/bin\/transmission-daemon/ {found=1} found && /--logfile/ {print; exit}' /run/s6-rc/servicedirs/svc-transmission/run)" ]]; then
  echo "Will add logging and restart the service. Check the /config folder in a few seconds."
  sed -i 's|-g /config -f|-g /config -f --log-debug --logfile /config/transmission.log|g' /run/s6-rc/servicedirs/svc-transmission/run
  ps aux | grep transmission-daemon | grep bin | awk '{print $2}' | xargs kill
else
  echo "File does not exist or --logfile already exists after /usr/bin/transmission-daemon."
fi
```

then make it executable in your host 

Finally run from your host 

`docker exec -it transmission /config/start_logging.sh`

Logging should start a few seconds later in the /config folder in the host.
