### ISSUE TITLE
Raspberry PI (armhf) DNS problem on alpine 3.13

### ISSUE THREAD

**Issue by zarmhast** [linuxserver/docker-transmission#156]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Transmission should contact trackers and seek out peers

## Current Behavior

Transmission does not even attempt to contact trackers as it cannot resolve DNS

## Steps to Reproduce

1. Use Raspberry PI 32 bit
2. Run image in docker
3. Add a torrent to transmission OR attempt to `curl` any http address from the container

## Environment
**OS:** raspbian 10 (buster)
**CPU architecture:** arm32
**Image ID:** `6cd1fc6457ff`
**How docker service was installed:** official instructions via apt-get

## Command used to create docker container (run/create/compose/screenshot)

`docker run --rm -it --entrypoint bash linuxserver/transmission`

## Docker logs

> /# apk update
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz
> ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz
> ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory
> 2 errors; 33 distinct packages available

**Comment by zarmhast** [comment]
@Roxedus, thank you for taking note of my issue in such a short time. But would you be so kind as to provide some details into why this is invalid?

**Comment by Roxedus** [comment]
Missing full container logs.

**Comment by zarmhast** [comment]
@Roxedus, you must be referring to this portion of the logs:

> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> 
> Your DockerHost is most likely running an outdated version of libseccomp
> 
> To fix this, please visit https://docs.linuxserver.io/faq#libseccomp
> 
> Some apps might not behave correctly without this
> 
> @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Thank you for pointing it out, still to me this is a broken image if it does not support docker OOTB and requires installation of unstable packages.

**Comment by Roxedus** [comment]
It is your host that is broken. Libseccomp is blocking a syscall because of a bug in the version on your host, this bug is resolved in newer versions of the package, which is not in the main repos for some reason.

**Comment by aptalca** [comment]
> still to me this is a broken image if it does not support docker OOTB and requires installation of unstable packages

Docker has its own dependencies and in this case it's one of those dependencies on your host that is outdated/broken. The newer package is in the official backports repo. We are not trying to tell you to install some random package.
