### ISSUE TITLE
Date issue on ARM

### ISSUE THREAD

**Issue by pr3d1** [linuxserver/docker-transmission#157]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

I downloaded the image, and tried with my Raspberry Pi 4. The torrent download was not working, so i started debugging. I presume the problem is the following:

_root@fdd39f2940d0:/# date
Thu Jan  1 01:00:00 BST 1970
root@fdd39f2940d0:/# ping github.com
ping: bad address 'github.com'
root@fdd39f2940d0:/# nslookup github.com
nslookup: clock_gettime(MONOTONIC) failed_

The container's clock starts from the 0 unix timestamp. Tested the image with this parameter: " -v /usr/share/zoneinfo/Europe/Budapest:/etc/localtime:ro", it didn't help.
I tried the image on my AMD64 architecture computer, the problem did not occur there.

------------------------------

## Expected Behavior
Transmission's clock is working funny on ARMv7l architecture. I think this causes my problem.

## Current Behavior
Transmission can't download from anywhere.

## Environment
**OS: Raspbian GNU/Linux 10**
**CPU architecture:** armv7l
**How docker service was installed:**
/etc/apt/sources.list.d/docker.list: deb [arch=armhf] https://download.docker.com/linux/raspbian buster stable
sudo apt-get install docker docker-ce docker-ce-cli

Docker version 20.10.5, build 55c4c88
I don't have this kind of problem with any other linuxserver image.

## Command used to create docker container (run/create/compose/screenshot)
docker run -d   --name=transmission   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London   -e TRANSMISSION_WEB_HOME=/combustion-release/   -p 9091:9091   -p 51413:51413   -p 51413:51413/udp   -v /home/pi/config/transmission:/config   -v /mnt/Seagate/tmp/:/downloads --network prod   --restart unless-stopped ghcr.io/linuxserver/transmission

## Docker logs
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by j0nnymoe** [comment]
It's telling you how to fix it in the log.

**Comment by Trisky** [comment]
It may be related to this issue:

https://docs.linuxserver.io/faq#libseccomp

**Comment by pr3d1** [comment]
Many thanks, this package solved my problem.
