### ISSUE TITLE
README file docker-compose 

### ISSUE THREAD

**Issue by AugustasV** [linuxserver/docker-transmission#158]
Had to make some changes for this docker-compose usage file, in order to work properly. Docker-compose version should be 2, not 2.1. Also restart behavior changed to always. 

------------------------------
```
@tests-MacBook-Pro ➜ va  kompose convert

FATA Version 2.1 of Docker Compose is not supported. Please use version 1, 2 or 3
@tests-MacBook-Pro ➜ va  nano docker-compose.yaml
@tests-MacBook-Pro ➜ va  kompose convert

WARN Restart policy 'unless-stopped' in service transmission is not supported, convert it to 'always'
INFO Kubernetes file "transmission-service.yaml" created
INFO Kubernetes file "transmission-deployment.yaml" created
INFO Kubernetes file "<path to data>-persistentvolumeclaim.yaml" created
INFO Kubernetes file "<path to downloads>-persistentvolumeclaim.yaml" created
INFO Kubernetes file "<path to watch folder>-persistentvolumeclaim.yaml" created
```
Oh ok, so this is only then tried to reproduce using kompose - tool to convert the docker-compose file to be usable on Kubernetes. So this issue is only related to kompose tool, or also docker-transmission?

**Comment by j0nnymoe** [comment]
please could provide us with some insight/justification why these bits would need to be changed.

**Comment by AugustasV** [comment]
> Please could provide us with some insight/justification why these bits would need to be changed.
> Marked invalid as issue template that requests information was ignored.

Thank you, updated but, those changes would make easier to run docker-transmission on kubernetes.

**Comment by Roxedus** [comment]
The compose example is not compatible with compose v2. It is a perfectly valid docker compose file using version 2.1.

As for the restart part, I really dislike `always`, it can come back to hunt you.
