### ISSUE TITLE
No symbolic link for python

### ISSUE THREAD

**Issue by Jelmerb** [linuxserver/docker-transmission#159]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Python command is available, but python3 is. NzbToMedia calls python so fails to run.
I have created a symbolic link myself but I am afraid that it will be lost with an update for this container. 

------------------------------

## Expected Behavior

Python command should be able to be called

## Current Behavior

Python is not recognized 

## Steps to Reproduce

1.call python with any script.
2.
3.
4.

## Environment
**OS:DSM** 6.2.4
**CPU architecture:** x86_64/
**How docker service was installed:** nas OS provided

## Docker logs

env: ‘python’: No such file or directory | stdout
-- | --

**Comment by Roxedus** [comment]
Doing this symlink is bad practice, and might result in unwanted side-effects. The safe way to do this is to update the shebangs in your scripts.

**Comment by Jelmerb** [comment]
Thanks for the reply, that is a hell of a job.

**Comment by Roxedus** [comment]
Either push them to update their shebang (python2 went EOL over a year ago), or keep the unsafe modification, with your [own script](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/).

**Comment by Jelmerb** [comment]
Thanks for the advice. I'll pass on the suggestion. For now i'll change the shebangs myself. Shouldn't be to hard to achieve with a few commands.
