### ISSUE TITLE
Add option to run script torrent done filename when torrent is completed

### ISSUE THREAD

**Issue by shudack** [linuxserver/docker-transmission#160]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Could you please add a ENV to script-torrent-done-enabled and script-torrent-done-filename to run script when torrent is completed?
The script it will unrar or unzip the torrent downloaded.

## Current Behavior
I can't write in settings.json because is overwritten when the container is started

## Alternatives Considered
Add a ENV:
- script-torrent-done-enabled (boolean)
- script-torrent-done-filename (string)

**Comment by j0nnymoe** [comment]
If the settings.json is getting overwritten, you're apply the wrong permissions to that file that is causing the container to do it.

**Comment by shudack** [comment]
> If the settings.json is getting overwritten, you're apply the wrong permissions to that file that is causing the container to do it.
> https://github.com/linuxserver/docker-transmission/blob/262dfc17042ea14ae2618b8a5a9f6a3a67224ef7/root/etc/cont-init.d/20-config#L8

Opsss.. I stopped the container, changed the settings.json, started the container again, and the values is not overridden.

Thanks @j0nnymoe !
