### ISSUE TITLE
No network connection armhf

### ISSUE THREAD

**Issue by Tloxipeuhca** [linuxserver/docker-transmission#163]
![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)

------------------------------

## Expected Behavior

Start to download a torrent

## Current Behavior

Torrent does not start downloading.
<img width="692" alt="i1" src="https://user-images.githubusercontent.com/9784436/117347440-69a41880-aea9-11eb-8840-1ee608932859.PNG">

## Steps to Reproduce

1. Command: "docker-compose up -d"
2. Upload Torrent Files

## Environment
Raspberry Pi 3 Model B Rev 1.2
arm32
Docker version 19.03.13, build 4484c46
docker-compose version 1.29.1, build unknown

## Command used to create docker container (run/create/compose/screenshot)

version: "2.1"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=myuser
      - PASS=mypassword
    volumes:
      - /home/pi/docker-data/transmission3/config:/config
      - /home/pi/transmission/downloads:/downloads
      - /home/pi/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

### Steps

1. Sh: docker-compose up -d
2. IHM: torrent file
3. Sh: docker-compose exec transmission sh
4. Sh: ping 127.0.0.1

### Result
```
root@b01ae7372833:/# ping 127.0.0.1
PING 127.0.0.1 (127.0.0.1): 56 data bytes
ping: clock_gettime(MONOTONIC) failed
root@b01ae7372833:/#
```

### My idea
Update docker form image to latest alpine armhf version.

**Comment by Roxedus** [comment]
Please fill the issue template

**Comment by Tloxipeuhca** [comment]
Thank you, i have updated the issue :)

**Comment by Tloxipeuhca** [comment]
Thank you very much 👍

**Comment by jurgislipsnis** [comment]
I have the same problem - Your DockerHost is most likely running an outdated version of libseccomp

How to update the libseccomp?

**Comment by j0nnymoe** [comment]
It gives you a link in the log to follow...

**Comment by jurgislipsnis** [comment]
Yes, I see, but where/how to run those update commands if I have OpenMediaVault + Portainer web interface?

**Comment by j0nnymoe** [comment]
Login to omv via ssh.

**Comment by jurgislipsnis** [comment]
just run those commands on omv?
Im bit afraid if it wont affect other container work. I have running system with nextcloud, letsencrypt and mariadb containers running there

**Comment by j0nnymoe** [comment]
Yes, everything is explained in that link. You will hit this issue with any new containers.

If you're worried, make sure your data is backed up.
