### ISSUE TITLE
Delete Tracker

### ISSUE THREAD

**Issue by YasserAntonio** [linuxserver/docker-transmission#168]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

As the Transmission api allows it, it would be great if the  transmission's web UI could let the user delete the tracker's torrent when selecting it.
## Current Behavior

Trackers can on ly be showed when clicking on the antenna tower logo

**Comment by YasserAntonio** [comment]
Exemple on the Mac OS transmission app
<img width="755" alt="Capture d’écran 2021-07-11 à 23 38 35" src="https://user-images.githubusercontent.com/8104486/125210680-9efe2580-e2a1-11eb-9f13-3ced834656a7.png">

**Comment by 0b100100** [comment]
First of all this is not an issue of this repo.

The screenshot is the desktop client with an integrated UI, which differs from the headless transmission-daemon.

The transmission-daemon used in this docker image can be interacted with different Web-Interfaces like [`/combustion-release/`](https://github.com/Secretmapper/combustion), [`/transmission-web-control/`](https://github.com/ronggang/transmission-web-control), [`/kettu/`](https://github.com/endor/kettu) and [`/flood-for-transmission/`](https://github.com/johman10/flood-for-transmission).
Please consider reading the [README.md](https://github.com/linuxserver/docker-transmission/blob/master/README.md) file how to activate them.
A possible solution would be to use [`/transmission-web-control/`](https://github.com/ronggang/transmission-web-control) which has the option to delete trackers.

If you would like to use the default UI named [`/combustion-release/`](https://github.com/Secretmapper/combustion) you should consider opening an issue on their repo to ask for such a feature (https://github.com/Secretmapper/combustion).

**Comment by YasserAntonio** [comment]
Thank you for your detailed reply.  I will try another Web-Interfaces then.
