### ISSUE TITLE
the transmission container only efficiently uses one core

### ISSUE THREAD

**Issue by sagatxxx** [linuxserver/docker-transmission#169]
Hello everybody.

I have installed omv5 and the transmission container always puts one core at 100% but the other cores are almost doing nothing, so the performance is very poor with the downloads and the service works quite bad!

I have tried adding it to use all 4 cores, but it has not worked
i have a Intel NUC BOXNUC6CAYH, Celeron J3455

What I can do? Thank you

this is my transmision stack:

> ---
> version: "2.1"
> services:
>   transmission:
>     image: ghcr.io/linuxserver/transmission
>     container_name: transmission
>     environment:
>       - PUID=998
>       - PGID=100
>       - TZ=Europe/Madrid
>       - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
>       - USER=xxx  #optional
>       - PASS=xxx! #optional
>     volumes:
>       - /srv/dev-disk-by-uuid-64f941a1-9045-4318-a332-0df66b2b2a1a/config/transmission:/config
>       - /srv/dev-disk-by-uuid-64f941a1-9045-4318-a332-0df66b2b2a1a/descargas:/downloads
>     ports:
>       - 9091:9091
>       - 51413:51413
>       - 51413:51413/udp
>     restart: unless-stopped
>     deploy:
>       resources:
>         limits:
>           cpus: 4

![Captura de pantalla 2021-07-11 a las 11 10 07](https://user-images.githubusercontent.com/20211038/125630264-8b99b05c-121f-4194-850b-7b959d412c9c.png)

**Comment by j0nnymoe** [comment]
Looks like transmission isn't multi threaded https://github.com/transmission/transmission/issues/1238

**Comment by sagatxxx** [comment]
> Looks like transmission isn't multi threaded [transmission/transmission#1238](https://github.com/transmission/transmission/issues/1238)

how can i fix? 

The same thing happens to me as the post you mention, I don't get speeds above 20Mb / sec and the response of everything is very slow, could I lower the buffer size or something similar?

**Comment by j0nnymoe** [comment]
Can't fix something they don't support. You would need to read transmission documentation on how to optimise I guess or switch clients.

**Comment by sagatxxx** [comment]
what surprises me is if I install transmission outside of cocker everything works correctly and the speeds are ok

**Comment by ckerr** [comment]
Closing as a dupe of https://github.com/transmission/transmission/issues/2462. I realize this ticket was filed before 2462, but there are so many overlapping tickets at this point that it makes sense to start with a new "big picture" ticket.
