### ISSUE TITLE
Could not connect to tracker DSM 7.0-41890

### ISSUE THREAD

**Issue by fkocovski** [linuxserver/docker-transmission#171]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Torrents should be connecting to trackers

## Current Behavior

Torrents do not connect to trackers.

![image](https://user-images.githubusercontent.com/9000611/130592103-f7ed347f-eeb9-410b-bfc4-18790a306321.png)

## Steps to Reproduce

1. Install from latest tag
2. Configure following steps on docker hub
3. Firewall settings
4. Port forwarding

## Environment
**OS:** DSM 7.0-41890
**CPU architecture:** x86_64/arm32/arm64 DS218+ INTEL Celeron J3355
**How docker service was installed:**

## Docker logs

24.08.21 09:20 | stdout | [2021-08-24 11:20:03.310]   ubuntu-21.04-desktop-amd64.iso Retrying announce in 20 seconds.   (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)

24.08.21 09:20 | stdout | [2021-08-24 11:20:03.309] ubuntu-21.04-desktop-amd64.iso Could not   connect to tracker   (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)
  
24.08.21 09:20 | stdout | [2021-08-24 11:20:03.309] ubuntu-21.04-desktop-amd64.iso Retrying   announce in 20 seconds.   (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1094)

24.08.21 09:20 | stdout | [2021-08-24 11:20:03.309] ubuntu-21.04-desktop-amd64.iso Could not   connect to tracker   (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1085)

**Comment by j0nnymoe** [comment]
Please could you provide screenshots of the DSM gui? It sounds like something is misconfigured in terms of network access.

**Comment by fkocovski** [comment]
Ok I fixed this as per your suggestion by activating the checkbox in the container that says "Use the same network as Docker host"
