### ISSUE TITLE
Changing settings.json during docker build

### ISSUE THREAD

**Issue by MikeVlad6** [linuxserver/docker-transmission#173]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Right now i got it working by:
- Building/Starting the container
- Stopping the container
- Editing /config/settings.json and changing:
-    - "script-torrent-done-enabled" -> true
     - "script-torrent-done-filename" -> "/torr_finished_routine.sh"'
     - "incomplete-dir-enabled" -> false
- Restarting the container.
I would like to achieve the same result by using a script placed in /config/custom-cont-init.d as per your instructions.

## Current Behavior
The same issue i've seen in other posts, the settings get overwritten.

## Steps to Reproduce
I've written this dockerfile:
```
FROM ghcr.io/linuxserver/transmission

# Add routine to change transmission settings.
COPY torr_service/change_transmission_settings.sh ./config/custom-cont-init.d/
RUN chmod +x ./config/custom-cont-init.d/change_transmission_settings.sh
RUN chmod 777 ./config/custom-cont-init.d/change_transmission_settings.sh
```
Where `change_transmission_settings.sh` looks like this:
```
#!/bin/bash

jq '."script-torrent-done-enabled" = true' /defaults/settings.json
jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /defaults/settings.json
# test 1231
jq '."incomplete-dir-enabled" = false' /defaults/settings.json
```
I've also tried with `config/settings.json` instead of `defaults`. I've also tried with `environment variables` in any way imaginable. I've also tried running this commands directly in the dockerfile but without any success.

Question is: Is there `ANY WAY` in which we can change those settings at the docker build moment? 

## Environment
Docker on Ubuntu

**Comment by Roxedus** [comment]
You cannot modify a file in /config during build.

**Comment by aptalca** [comment]
As rox said, you can't modify files on config during build, however you can modify /defaults/settings.json during build and the modified file will be copied to config on first start

**Comment by MikeVlad6** [comment]
@aptalca & @Roxedus thanks for your reply. According to this, and according to [this info](https://www.linuxserver.io/blog/2019-09-14-customizing-our-containers) about Custom Scripts in linuxserver's dockers, if i were to make a `.sh` file and place it in `/config/custom-cont-init.d` this would be ran on docker startup, right before initializing the services (which it does). So any of the following two approaches should work:
1. Make a `.sh file with the following contents:
```
#!/bin/bash

jq '."script-torrent-done-enabled" = true' /defaults/settings.json
jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /defaults/settings.json
jq '."incomplete-dir-enabled" = false' /defaults/settings.json
```
and place this script in the appropriate folder:
```
FROM ghcr.io/linuxserver/transmission

#  Add routine to change transmission settings.
COPY torr_service/change_transmission_settings.sh ./config/custom-cont-init.d/
RUN chmod +x ./config/custom-cont-init.d/change_transmission_settings.sh
RUN chmod 777 ./config/custom-cont-init.d/change_transmission_settings.sh
```
The jq commands simply changes the values for the keys provided.
 **OR**
2. Include those commands right in the dockerfile configuration:
```
FROM ghcr.io/linuxserver/transmission

RUN jq '."script-torrent-done-enabled" = true' /defaults/settings.json
RUN jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /defaults/settings.json
# test 1231
RUN jq '."incomplete-dir-enabled" = false' /defaults/settings.json

I've attached here the output from (i) building the docker, (ii) running the docker and (iii) the final state of /config/settings.json while the docker is running.  The changes are being made during build but are reverted on service startup. The same output is when including the commands inside the `dockerfile` itself. Is there something i'm missing?

Thanks again!
[option1_output.txt](https://github.com/linuxserver/docker-transmission/files/7111013/option1_output.txt)

**Comment by Roxedus** [comment]
`custom-cont-init.d` is not intended for use in `buildtime`, what you want is to take the mod approach.

**Comment by MikeVlad6** [comment]
Ok, I understand. Thanks for your help and for all the hard work that goes into these containers. I've taken a look at `mods` and i'm gonna try, i understand that i might get some help on discord channel. If i get to the end of it i'll post the solution here, maybe someone will use it in the future.

**Comment by MikeVlad6** [comment]
I'll leave my steps here, they're a very noob approach as compared to the tutorial [here](https://github.com/linuxserver/docker-mods) but maybe they'll shed some light to some noobs like me and cut from those long hours:)

This mod only changes settings.json in transmission.
The files needed to build the mod can be found [here](https://github.com/MikeVlad6/transmission_mod).

1. Create a public repo on dockerhub (public), mine is mikael6/just_fun:transmission_mod. Change the names to your docker repo as in {username}/{repo}:{your_whatever_tag}.
2. `docker build -t mikael6/just_fun:transmission_mod` when you've cloned the repo above.
3. `docker push mikael6/just_fun:transmission_mod`
4. So right now you have a mod which is going to change the `defaults.json` used by transmission on
startup.
5. You need to create this container:
`docker create --name=test -e PUID=1000 -e PGID=1000 -e DOCKER_MODS=mikael6/just_fun:transmission_mod --restart unless-stopped linuxserver/transmission`
It will return a container ID
6. `docker start {ID}` that ID. You can open a CLI into the container and use `cat defaults/settings.json` and `cat config/settings.json` to see that your configs have been saved.
