### ISSUE TITLE
setting.json gets overwritten at every start

### ISSUE THREAD

**Issue by fbc** [linuxserver/docker-transmission#177]
What's the point of mapping a persistent volume for it, if it's going to get overwritten with ever restart of the stack.

**Comment by aptalca** [comment]
It doesn't randomly get overwritten. It gets overwritten with the settings used while the app is shutting itself down. The same settings are read when started. So they are persistent.

**Comment by fbc** [comment]
I've made a change to.. shut the contianer down. It does not over write at that point. When I start it up , it gets over written.

For example, shut it down. Make a change to the location of our download dir and start it back up. Then open your settings.json in your persistent volume and see that it has reverted back.
