### ISSUE TITLE
Very slow disk I/O

### ISSUE THREAD

**Issue by jaytrinitron** [linuxserver/docker-transmission#178]
I am not sure this is an issue, maybe it is something with my personal setup.
I have found so far that disk I/O activities take forever from the docker container, and I'm not sure why. Particularly, verification takes much longer than it should. While it does peg one thread at 85-100% usage, I believe transmission's lack of multithreading is unrelated, because a transmission instance installed on bare metal performs quite well in comparison (8-10x speed). Disk activity does not seem to go higher than 20MB/s, and is usually closer to 10-15. My internet download speed is fast enough that disk I/O is usually the bottleneck, provided the torrent has high-speed/many seeders. Is there a setting I can try to fix this? It happened on my old system as well, and I just chalked it up to it being extremely old. But my new system should not be disk I/O limited to this extent. What gives?

Edit: So after monitoring it seems like for very large torrents the disk read starts out high enough (around 100MB/s) before dropping off over time. My disks are not full, and the highest speed is still about half of what I get on bare metal.

**Comment by j0nnymoe** [comment]
You've ignored our issue template where we ask information about your setup... We aren't able to help without that.

**Comment by jaytrinitron** [comment]
Sorry about that, for some reason it didn’t autofill a template and I didn’t realize when looking at past issues.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]





------------------------------

## Expected Behavior
Transmission in docker has roughly the same read and write speed as transmission on bare metal.
## Current Behavior
For verification of large (multiple hundreds of GB) torrents, docker transmission starts out already slow (half speed) before dropping speed over time to a crawl (15 MB/s)
## Steps to Reproduce


1. Get a very large torrent and verify
2. Compare against speed of native transmission for the same process

## Environment
**OS:**
Ubuntu 20.04.3 LTS
**CPU architecture:** x86_64
**How docker service was installed:**
from the official docker repo


## Command used to create docker container (run/create/compose/screenshot)


## Docker logs

**Comment by j0nnymoe** [comment]
Are you checking cpu usage and io usage while the transfer is slowing down?

**Comment by j0nnymoe** [comment]
It's probably how you've got your volumes setup. If it's 2 separate mounts, it's gonna cause more io.

**Comment by thelamer** [comment]
We install transmission from Alpine's repos. I am just stating that to break down what we do here is not exactly rocket science. 
I can appreciate that you are having a real issue while running this in Docker vs running it natively, but I do not believe we will be able to resolve this issue by making modifications to this codebase.
