### ISSUE TITLE
Set ports by environmental variables (webui & listening) 

### ISSUE THREAD

**Issue by jeff47** [linuxserver/docker-transmission#179]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

It would be very useful if the ports for the WebUI and listening ports could be specified via an environmental variable, rather than having to edit settings.json.  Is this possible?
------------------------------

**Comment by drizuid** [comment]
https://github.com/linuxserver/docker-transmission/pull/182 will address peerport if/when merged, we will not modify anything related to webui.

**Comment by thelamer** [comment]
PEERPORT was merged, thanks for that. As far as any other ports those should be mapped by docker.
