### ISSUE TITLE
multiple bugs, missing options

### ISSUE THREAD

**Issue by comet424** [linuxserver/docker-transmission#189]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

multiple bugs
1.. Active Page doesnt work
2.. you cant select select all
3.. ui just isnt as user friendly as the original.
4.. cant toggle alternate speeds like you used to

or an option to Toggle..  Classic mode thats always worked.. and this current setup

so like you have night and day..   this way people can use the classic orginal way.. and if they like the newer style.. all they need to do is toggle new style
------------------------------

## Expected Behavior

active pages should tell ya whats working
i should be able to left click and choose  select all on the torrents and then click resume all like orginal
be able to toggle alternate speeds easily..
new settings page not as simple as the orginal

## Current Behavior

activate pages doesnt work
left clicking doesnt work  all you can choose is resume  now
no options for find more trackers resume, select all, pause all etc

its more of a headache then it was.. settings was in a dice small box.. easy.. and a drop down box for Active Pause Downloads Seeding
an a button to toggle on and off settings,alternate speeds..  and be able to left click and have select all and all the same options

should just go back orginal way.  as long as transmission works no need to change it..  but thats what i found
is there a way to downgrade back to the working version?

## Steps to Reproduce

1.  just load it up  and do the left clicking clicking Active   in the side panel
2.  its more of a headache then it was.. before was just simple
3.
4.

## Environment
**OS:**  Unraid
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Unraid Docker

## Command used to create docker container (run/create/compose/screenshot)

Gui Unraid install

**Comment by Roxedus** [comment]
This is not a container issue. You can find earlier tags on DockerHub https://hub.docker.com/r/linuxserver/transmission/tags

**Comment by comet424** [comment]
what does it mean not a container issue?   where do i report the problems of the latest transmission bugs in the gui then?
what link do i report it to to have it fixed? and request the feature of the 2 types of gui classic and new?
unraid only links this page as the support page for the transmission

**Comment by Roxedus** [comment]
You report transmission bugs to transmission. https://transmissionbt.com/

**Comment by comet424** [comment]
ah ok.. guess unraid needs to fix transmission support page to goto the transmissionbt  website not here then for support and bug reports.

thanks.. ill report above issues there.. 
have a great day
