### ISSUE TITLE
umask for transmission configuration

### ISSUE THREAD

**Issue by gladiacxtylish** [linuxserver/docker-transmission#192]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
The transmission `settings.json` has a field `umask` for setting the file umask for the download files.

## Current Behavior
Currently, there is no way to set this value, and the default is always set to `2`.

## Alternatives Considered
The documentation states a config `Umask for running applications`, but that is the umask for something else.

**Comment by thelamer** [comment]
In general there are a lot of settings in settings.json. Instead of making env vars for them or substituting in on config would it not make more sense for power users to simply either edit this file directly or mount what they want in ?

**Comment by gladiacxtylish** [comment]
I try to avoid manual editing the file to achieve automating the process. Is there a way to have a generic way to set the config values, like a key value map, that way maintainers do need to have an env var for each config.
