### ISSUE TITLE
403: Too many unsuccessful login attempts. Please restart transmission-daemon

### ISSUE THREAD

**Issue by luckiestone** [linuxserver/docker-transmission#195]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Webui connecting without issue.

## Current Behavior
Pops up "403: Too many unsuccessful login attempts. Please restart transmission-daemon"

## Steps to Reproduce

Nothing special, maybe scanned too many times by some random online scanners.

## Environment
**OS: DSM 7.0.1
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

Official docker service on DSM918+

## Command used to create docker container (run/create/compose/screenshot)

Nothing special using GUI

## Docker logs

No need.
This issue is related to this one: https://github.com/transmission/transmission/issues/1415 . However, I have no idea how this affects the docker version.

**Comment by cikichen** [comment]
+1 
Too many unsuccessful login attempts. Please restart transmission-daemon.

**Comment by j0nnymoe** [comment]
This was marked an invalid issue because the original poster did not provide all the information requested.

**Comment by drizuid** [comment]
template not filled out
