### ISSUE TITLE
Removal of some environment variables

### ISSUE THREAD

**Issue by hacketiwack** [linuxserver/docker-transmission#198]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

The following optional environment variables are removed:
- USER=username #optional
- PASS=password #optional
- WHITELIST=iplist #optional
- PEERPORT=peerport #optional
- HOST_WHITELIST=dnsname list #optional

## Current Behavior

Currently, there are multiple optional environment variables that can be set at the container creation time:
- USER=username #optional
- PASS=password #optional
- WHITELIST=iplist #optional
- PEERPORT=peerport #optional
- HOST_WHITELIST=dnsname list #optional

Defining these settings are container creation time causes the following difficulties:
- Security: the password should not be passed through environment variables.
- Collision of configuration: when setting the whitelist, host whitelist and user at the container creation, each time the container is restarted, the configuration made by the user is replaced with the values of the afore mentioned environment variables.
- Coherence: for the sake of coherence during the process of configuring Transmission, this would be much easier for the user to only configure their `settings.json` configuration file than doing it during the creation of the container.

Therefore, this could lead to some confusion between the `settings.json` configuration file and the configuration done at the container creation. The configuration made at the container creation and subsequently at every restart of the container (see 20-config) overwrite the parameters set by the user after the container start up.

Users are responsible to maintain their `settings.json` files.

## Alternatives Considered

None.

**Comment by aptalca** [comment]
I personally have no interest in being part of a tug of war between a group of users who want everything managed via env vars and another group who want everything managed through the settings file. What we have now is a decent compromise where most of the basics can be managed via vars and the rest can be done via editing the settings file.

**Comment by hacketiwack** [comment]
In this case, there is an improvement that should be done in the init file `20-config` in this case that would not destroy the user configuration if theses variables are set directly in the `settings.json` file.

**Comment by elvismercado** [comment]
This issue is very annoying.

I use unraid. So i add this app via  the unraid app templates.
I just need to be able to open the application. So I remove the USER, PASS, WHITELIST, HOST_WHITELIST and PEERPORT from the template. And create the container  like that.
At every restart these settings come back with defaults which break the app so it wont even start.

An example is `WHITELIST=iplist` is put back from the template at restart. Of course this value is not a string and the container fails to start.
Doing the same via the settings.json resets these values in the settings json through the env variables.

So sinsce the last update i haven't been able to use this app anymore, which is a shame.

**Comment by j0nnymoe** [comment]
@elvismercado No, you're issue is actually an unraid issue, not the container environment variables. Disable the unraid template sync and this will stop happening.

**Comment by elvismercado** [comment]
Thank you for the suggestion. This will surely help me.
