### ISSUE TITLE
transmission 下载文件位置问题

### ISSUE THREAD

**Issue by wl3768** [linuxserver/docker-transmission#199]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

下载文件能在配置的目录内！

## Current Behavior

配置的目录：“   -/mnt/sdb1/transmission/download:/downloads”
实际下载的文件到了，
“/mnt/sda1/Docker/btrfs/subvolumes/8d683f73ba3efd0702d4a8eee70d757b6e42f96e9d4ff0aacebf0e480a938348/mnt/sdb1/download/”
只是下载的文件全部在容器内的路径下！
配置文件.config在我写的配置位置
## Steps to Reproduce

没做多余的操作，只是在原有的配置文件修改目录和webui，用户和密码.
`docker run -d \
  --name=transmission \
  -e PUID=0 \
  -e PGID=0 \
  -e TRANSMISSION_WEB_HOME=/combustion-release/ \
  -e USER=admin \
  -e PASS=adminadmin \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v /mnt/sdb1/transmission:/config \
  -v /mnt/sdb1/download:/downloads \
  -v /mnt/sdb1/transmission/watch:/watch \
  --restart unless-stopped \
  lscr.io/linuxserver/transmission:latest `

## Environment
**OS:**openwrt
**CPU architecture:** arm64
**How docker service was installed:**docker run -d

## Command used to create docker container (run/create/compose/screenshot)

![DC6DF452-1188-4F76-A96F-242A2CE2DE2C](https://user-images.githubusercontent.com/72538933/169819263-480d2d45-2393-4a98-95cf-efef8824d6ce.png)
![54F41E1B-101E-49FD-A40D-8D24A627321D](https://user-images.githubusercontent.com/72538933/169819277-5c6758f4-f78c-4eb5-8395-76cf3633e23b.png)
![C688BC67-73F6-4491-9FDE-3A5AD804922C](https://user-images.githubusercontent.com/72538933/169819280-daf8a310-0855-4d94-a48b-212e8cee413b.png)
![ACC96C43-6F58-4DE8-9768-DFFA916BAE09](https://user-images.githubusercontent.com/72538933/169819290-a9eb19f6-4bfc-468b-ba68-38ebeac478c8.png)
![D8C5D9D3-7922-434D-9797-EC8E0BF40D62](https://user-images.githubusercontent.com/72538933/169819540-49e29e7f-f80a-4000-9207-bc0cc718b686.png)

**Comment by Roxedus** [comment]
Please provide some context on English.

**Comment by wl3768** [comment]
The download file can be in the configured directory.
Configured directories:
`-/mnt/sdb1/transmission/download:/downloads`
The actual downloaded file arrived:
`/mnt/sda1/Docker/btrfs/subvolumes/8d683f73ba3efd0702d4a8eee70d757b6e42f96e9d4ff0aacebf0e480a938348/mnt/sdb1/download/`
Just download the files all under the path inside the container!
The configuration file .config is where I wrote it

**Comment by Roxedus** [comment]
download-dir should be /downlads, as that is the path inside the cointainer poiting to /mnt/sdb1/download/ on the host.

**Comment by wl3768** [comment]
`settings.json`The file is in the configuration directory.
![屏幕截图 2022-05-23 204420](https://user-images.githubusercontent.com/72538933/169822130-e2819a3e-b788-405a-bad2-a1f3d04cca81.png)

**Comment by wl3768** [comment]
"download-dir": "/mnt/sdb1/download",
Changed to

    "download-dir": "/mnt/sdb1/downloads",

？？？

**Comment by drizuid** [comment]
> why ‘settings.json’and watch Files will be placed on local disk, only download files in the container?

because you broke your settings.json. change download-dir to /downloads and it will download to /mnt/sdb1/download
