### ISSUE TITLE
Default directories are re-created unnecessarily

### ISSUE THREAD

**Issue by hacketiwack** [linuxserver/docker-transmission#200]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

A user has the ability to decide where their downloads - completed and incomplete - will be stored.
This also applies to the watch directory.
The configuration is made in the `settings.json` through the GUI.
Whenever the container is restarted, the default directories, named `complete`, `incomplete` and `watch`, must not be re-created if the user has set different ones in their configuration (`settings.json`).

## Current Behavior

Currently, even if the user changed these directories and set them to different locations, the default ones are re-created for no reason.

## Steps to Reproduce

1. Start the container with the default configuration. The default directories are created.
2. Change the default directories to user-specific locations (parameters are `download-dir`, `incomplete-dir`, and `watch-dir`)
3. Delete the default directories.
4. Restart the container. 
5. The default directories are created again.

## Environment
**OS:** All
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

As explained in the documentation.

## Command used to create docker container (run/create/compose/screenshot)

Same as in the documentation.

## Docker logs

No logs are relevant for this issue.

**Comment by hacketiwack** [comment]
Please note that this [pull request](https://github.com/linuxserver/docker-transmission/pull/197) has been made to specifically solve this problem.

**Comment by drizuid** [comment]
https://github.com/linuxserver/docker-transmission/pull/197#issuecomment-1276161054
