### ISSUE TITLE
unregister_netdevice kernel message after restarting container

### ISSUE THREAD

**Issue by realivanjx** [linuxserver/docker-transmission#205]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

im getting a lot of this kernel messages on my ssh terminal that says:
```
Message from syslogd@home-server at Aug 13 15:06:36 ...
 kernel:[614037.260262] unregister_netdevice: waiting for lo to become free. Usage count = 1
```
that happens everytime i restarted the transmission container. the message will only go away if i reboot the docker host. here is my docker daemon config:
```
{
    "dns": ["8.8.8.8", "8.8.4.4"],
    "ipv6": true,
    "experimental": true,
    "ip6tables": true,
    "fixed-cidr-v6": "fd00::/80"
}
```

------------------------------

## Expected Behavior
no kernel messages after rebooting container

## Current Behavior
giving a lot of kernel messages described above

## Steps to Reproduce

1. run the container
2. reboot the container using docker restart command

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** arm64
**How docker service was installed:**

official docker website guide

## Command used to create docker container (run/create/compose/screenshot)

    transmission:
        image: xxxx
        restart: always
        ports:
            - 51413:51413/tcp
            - 51413:51413/udp
        environment:
            PUID: "1000"
            PGID: "1002"
            USER: "x"
            PASS: "x"
        volumes:
            - /data/x1:/config
            - /data/x2:/share

## Docker logs

-

**Comment by j0nnymoe** [comment]
Why have you blanked out the image name? For all we know you might not be using our container.

**Comment by realivanjx** [comment]
doesnt really matter but here you go: https://gitlab.com/ivanjx/transmission-flood/-/blob/master/Dockerfile

**Comment by j0nnymoe** [comment]
quick google shows that error is not related to our container but likely due to your changes in the daemon.json
https://github.com/moby/moby/issues/5618

**Comment by aptalca** [comment]
This section is for bug reports about our image, not general docker support. Closing.
