### ISSUE TITLE
How to skip torrent verification？

### ISSUE THREAD

**Issue by Ren-HK** [linuxserver/docker-transmission#206]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

What should I do to skip the seed verification. ? My file is very large and it takes a long time to verify。
------------------------------

**Comment by HCPlantern** [comment]
In Transmission 4.00 beta, newly-added torrents can skip the full verify step to save time and disk usage, so maybe you can wait for the 4.00 docker version.

**Comment by drizuid** [comment]
We support the container, not the application. Feature requests for the application should be made to the application devs. That said, as mentioned above 4x should offer this capability.
