### ISSUE TITLE
Is that possible to automatic update tracker list 

### ISSUE THREAD

**Issue by Vaayne** [linuxserver/docker-transmission#207]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

Maybe we can add a script to auto update tracker list like https://github.com/ngosang/trackerslist
There are some scripts we can leverage  
- https://github.com/AndrewMarchukov/tracker-add
- https://github.com/oilervoss/transmission
- …

And some tracker lists
- https://github.com/ngosang/trackerslist
- https://github.com/XIU2/TrackersListCollection

## Current Behavior

No auto update

## Alternatives Considered

If u are too busy for this, maybe I can try to take this.

**Comment by aptalca** [comment]
this would be a good candidate for a docker mod: https://github.com/linuxserver/docker-mods
If you submit a PR, we can publish in our mods list: https://mods.linuxserver.io/

**Comment by Vaayne** [comment]
Thanks @aptalca

**Comment by Vaayne** [comment]
@aptalca I create a [branch](https://github.com/Vaayne/docker-mods/tree/transmission-trackers) base on template, please help to create a branch for it.

**Comment by aptalca** [comment]
Sorry, I just realized we forgot to merge the hybrid PR to the template branch. It is now merged https://github.com/linuxserver/docker-mods/pull/507
Can you rebase your branch and make sure that it's a hybrid mod?

Thanks

**Comment by Vaayne** [comment]
sure

**Comment by djismgaming** [comment]
Is there a way to test this mod?
