### ISSUE TITLE
Restart if vpn goes down

### ISSUE THREAD

**Issue by Lexxior** [linuxserver/docker-transmission#209]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

I have transmission running in a compose file behind a vpn with the flags

    network_mode: service:vpn
    depends_on:
      - vpn
 
If the vpn goes down I would love transmission to restart or to reconnect with the vpn network
## Current Behavior

Currently transmission just keeps running and shows error that it couldn't connect to the peers

**Comment by spider1163** [comment]
Did you take a look at Haugene image?

https://github.com/haugene/docker-transmission-openvpn

**Comment by drizuid** [comment]
You will need to create your own script to handle this. You're welcome to create a docker mod which some script logic if you would like to share whatever you make.
