### ISSUE TITLE
Issue with s6-svscan crash

### ISSUE THREAD

**Issue by morgenst3rn** [linuxserver/docker-transmission#211]
Suddenly I can't start the container anymore.
Transmission config in my folder is not changed, but just in case I've also tried to use a default settings.json
I use portainer to manage my container, I've tried to recreate the container by scratch, also tried to launch manually via docker run, but I had the same issue.
The container stops immediately and this is what I can see from the logs

_s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted_

**Comment by thespad** [comment]
https://docs.linuxserver.io/faq#libseccomp
