### ISSUE TITLE
(Bug) mobile device browser: can’t simulate right click

### ISSUE THREAD

**Issue by SeveranExp** [linuxserver/docker-transmission#216]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

In iOS, using chrome, I’m unable to execute a right click. Press and hold, double tapping the screen neither work.
As it is I am unable to call up the contextual menu.
------------------------------

## Expected Behavior

Press and hold should open the contextual menu. 

## Current Behavior

Text is selected, or, a message pops up asking if I want to save the link/image.

## Steps to Reproduce

1. Open transmission web ui
2. Open contextual menu (press and hold a torrent)
3.
4.

## Environment
**OS:** Ubuntu 
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:** x86_64

## Command used to create docker container (run/create/compose/screenshot)

Followed Linuxserver example.

## Docker logs

Don’t have any errors. I just can’t open the contextual menu to manage my torrents :( there are posts for 2017 that hint was fixed in transmission though.

**Comment by drizuid** [comment]
template not filled out
