### ISSUE TITLE
Issue with blocklist update script

### ISSUE THREAD

**Issue by zaggash** [linuxserver/docker-transmission#22]
# copy blocklist-update script
**[[ ! -f /config/blocklist-update.sh ]] && cp \
	/defaults/blocklist-update.sh /config/blocklist-update.sh**

This is an issue if the script is updated.
The script wont be updated... this cause issue on client side.

When we are updating the images, we are not removing the mapped config folder so the script is not updated.

Kindly regards

**Comment by thelamer** [comment]
This is more complex than it looks on the surface, we need it in external storage as users want to modify it. And we cannot automate the upgrading of the script as users want to modify it. 
I appreciate the report, but we will not be changing the current logic, if the script changes in the future we will understand we need to support existing installations and devise a method of upgrading.
