### ISSUE TITLE
Busybox findutils package removed

### ISSUE THREAD

**Issue by stedju499** [linuxserver/docker-transmission#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Busybox findutils package was removed in https://github.com/linuxserver/docker-transmission/commit/0a7daf3f27c05026cbbf2dbc93d5f2a1d4b28250

It is needed for commonly used torrent-done unrar script:
find /$TR_TORRENT_DIR/$TR_TORRENT_NAME -name "*.rar" -execdir unrar e -o- "{}" \;

Could you please add it back?

### Steps To Reproduce

Download torrent with rar files and execute this as post script:
find /$TR_TORRENT_DIR/$TR_TORRENT_NAME -name "*.rar" -execdir unrar e -o- "{}" \;

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by thespad** [comment]
The Busybox `find` util is present OOTB. `findutils` is specifically the GNU find utilities package.

It looks like `-execdir` isn't supported by the busybox version, shouldn't be a problem to add the GNU package back in.
