### ISSUE TITLE
[FEAT] support Pre-release

### ISSUE THREAD

**Issue by lyj0309** [linuxserver/docker-transmission#223]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The transmission v4 is in Pre-release, i want it have a  Pre-release docker image

### Reason for change

Experience new features

**Comment by go2tom42** [comment]
v4 is no longer in Pre-release, it released today

**Comment by thespad** [comment]
Once the Alpine repos build v4 we'll pick it up and build it. Will probably be a few days at least.
