### ISSUE TITLE
[FEAT] Transmission 4.0

### ISSUE THREAD

**Issue by ai** [linuxserver/docker-transmission#225]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Release new version with Transmission 4.0

### Reason for change

Because [Transmission 4.0](https://github.com/transmission/transmission/releases/tag/4.0.0) has many excited features like better Web UI or better performance

**Comment by Roxedus** [comment]
We are need Alpine to build it before we can ship it. You can see the latest version [here](https://pkgs.alpinelinux.org/packages?name=transmission&branch=edge&repo=&arch=x86_64&maintainer=)

**Comment by go2tom42** [comment]
> We need Alpine to build it before we can ship it. You can see the latest version [here](https://pkgs.alpinelinux.org/packages?name=transmission&branch=edge&repo=&arch=x86_64&maintainer=)

released [4.0.0-r0](https://pkgs.alpinelinux.org/flag/community/transmission/4.0.0-r0)

**Comment by tmknight** [comment]
That's `edge`, we're currently based on 3.17

**Comment by ivanjx** [comment]
does transmission 4.0 not have logs like version 3?
