### ISSUE TITLE
[FEAT] Third-party UI packages as Docker Mods

### ISSUE THREAD

**Issue by pavelvodrazka** [linuxserver/docker-transmission#227]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Provide third-party UI packages as Docker Mods.

### Reason for change

Bundled third-party UI packages were removed from the 4.0.0 release. They can be added manually, but it would be nice to be able to add them easily with prepared mods.

**Comment by 568145697** [comment]
同求

**Comment by thespad** [comment]
I'll put together a mod for Flood because it's actually actively maintained. If people want mods for other themes they're welcome to make and publish them or submit them to our 1st party mods repo.

**Comment by pavelvodrazka** [comment]
@thespad Thank you very much! I'd love to see a mod for my favourite Transmission Web Control, but I understand it's not that active project. I'll take a look at your PR to see how difficult it is to create one.

**Comment by pavelvodrazka** [comment]
I don't think it's an inactive project. Probably just not updated so often.

**Comment by thespad** [comment]
Flood mod is now live https://github.com/linuxserver/docker-mods/tree/transmission-floodui

**Comment by Enissay** [comment]
`floodui` is cool, however, it freezes randomly and requires to refresh the page :-/
I hope `transmissionic` is added as well to have more choice
