### ISSUE TITLE
[FEAT] Add support for alternative Ui folders

### ISSUE THREAD

**Issue by Marck** [linuxserver/docker-transmission#228]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I use the TRANSMISSION_WEB_HOME: /combustion-release/ option in Tranmission.
In the new release, I get a warning that that isn't supported anymore, while the readme file still describes that it is.
I request a feature where UI folder is supported

<img width="963" alt="image" src="https://user-images.githubusercontent.com/18088281/218308296-c7cbd9be-d278-4254-9650-2bc998ce3016.png">

### Reason for change

To easily get UI folder support instead of creating a volume mount with the files for the different UI

### Proposed code change

It would be great if you just could use a URL and the container pulls the theme in the correct folder.
You now have to download the ZIP and put it in the correct place after the container/pod is created

**Comment by Marck** [comment]
Reopening as this could be a nice improvement for automatically downloading themes based on URLs

**Comment by Roxedus** [comment]
Mods is the supported way for alternate themes. https://mods.linuxserver.io/?mod=transmission
