### ISSUE TITLE
transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server[BUG] <title>

### ISSUE THREAD

**Issue by anarchopossum** [linuxserver/docker-transmission#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,
So I tried using the docker compose script given, only thing i have changed in the script is the download, config and watch folders to my mounted drive.

I ran `docker compose up` and i help getting this error
`transmission  | [2023-02-21 21:10:58.926] transmission-remote:  (http://localhost:9091/transmission/rpc/) Couldn't connect to server` and at the bottom `transmission  | tail: invalid PID: ‘’`
<img width="926" alt="image" src="https://user-images.githubusercontent.com/92814289/220460148-8d884567-42aa-46fd-8fe5-b59f065f6b90.png">

### Steps To Reproduce

1. make docker-compose file in ~/docker/transmission
2. Paste given compose info into compose file
3. modify the locations for downloads, config, and watch
4. run command `docker compose up`

### Environment

```markdown
- OS: Rasbian headless
- How docker service was installed:
generic docker one line install
```

### CPU architecture

arm64

### Docker creation

```bash
docker compose up
```

### Container logs

```bash
> docker logs linuxserver.io
Error response from daemon: No such container: linuxserver.io
```

**Comment by j0nnymoe** [comment]
You left the optional peer port variable in it unedited.

**Comment by anarchopossum** [comment]
> 
Sorry for the late response
I removed that portion of the config file. but i still get an `tail invalid PID` error.

Here is my Compose File


---
version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=username #optional
      - PASS=password #optional
      - "HOST_WHITELIST=dnsname list" #optional
    volumes:
      - /mnt/disk/Torrents/config:/config
      - /mnt/disk/Torrents/Downloads:/downloads
      - /mnt/disk/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

**Comment by drizuid** [comment]
> - "HOST_WHITELIST=dnsname list" #optional

you have a host_whitelist which is invalid

**Comment by drizuid** [comment]
closing, OP didn't read the readme and hasn't responded.
