### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by ollan** [linuxserver/docker-transmission#24]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Host OS: Ubuntu Server 16.04

I do not get the resume function in Transmission to work.
When restarting the Docker container I expect the ongoing torrent transactions to be resumed. Instead every torrent is removed. I can se that the resume directory contains multiple *.resume files. The files and directory are read and writable for everyone.

**Comment by lodgnewt** [comment]
i have same problem with this docker container. 
after restart container -  active torrents start downloading again, and those that are on pause keep progress.

**Comment by aptalca** [comment]
This seems to be an issue with transmission. 

Transmission-daemon should, upon receipt of SIGTERM, pause all active torrents, save the settings and shut down. Unfortunately if there are active torrents, transmission-daemon fails to stop correctly, gets stuck and then it's killed uncleanly by s6 manager.

If there are no active torrents, SIGTERM correctly results in transmission shutting down. This is indeed an issue with the daemon. I'll PR a patch to trap the TERM and send an exit command through transmission-remote.
