### ISSUE TITLE
[BUG] No informational logs

### ISSUE THREAD

**Issue by PHLAK** [linuxserver/docker-transmission#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Informational application logs are not shown when running `docker [compose] logs <container_name>` and `message-level` is greater than or equal to `2`. Only the LSIO banner and limited initial information are show (see Container logs section below).

### Expected Behavior

Informational application logs should be shown as they are generated.

### Steps To Reproduce

Set `message-level` to a value of `2` (or higher) in `settings.json`.

Run an instance of `linuxserver/transmission`.

Inspect the logs (`docker [compose] logs <container_name>`).

### Environment

```markdown
- OS: Arch Linux
- How docker service was installed: pacman
```

### CPU architecture

x86-64

### Docker creation

```bash
transmission:
  image: linuxserver/transmission
  depends_on:
    - wireguard
  env_file: config/transmission.env
  environment:
    PUID: 1000
    PGID: 2003
    TZ: America/Phoenix
  network_mode: service:wireguard
  volumes:
    - ./volumes/transmission:/config
    - /storage/downloads:/downloads
  restart: unless-stopped
```

### Container logs

```bash
transmission-1  | [migrations] started
transmission-1  | [migrations] no migrations found
transmission-1  | ───────────────────────────────────────
transmission-1  | 
transmission-1  |       ██╗     ███████╗██╗ ██████╗ 
transmission-1  |       ██║     ██╔════╝██║██╔═══██╗
transmission-1  |       ██║     ███████╗██║██║   ██║
transmission-1  |       ██║     ╚════██║██║██║   ██║
transmission-1  |       ███████╗███████║██║╚██████╔╝
transmission-1  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
transmission-1  | 
transmission-1  |    Brought to you by linuxserver.io
transmission-1  | ───────────────────────────────────────
transmission-1  | 
transmission-1  | To support LSIO projects visit:
transmission-1  | https://www.linuxserver.io/donate/
transmission-1  | 
transmission-1  | ───────────────────────────────────────
transmission-1  | GID/UID
transmission-1  | ───────────────────────────────────────
transmission-1  | 
transmission-1  | User UID:    1000
transmission-1  | User GID:    2003
transmission-1  | ───────────────────────────────────────
transmission-1  | 
transmission-1  | [custom-init] No custom files found, skipping...
transmission-1  | [ls.io-init] done.
```

No informational logs are ever shown, only occasional error logs.

**Comment by PHLAK** [comment]
After a little more troubleshooting I the following error message to show up (with `message-level` at `2`) but still no informational messages.

```
transmission-1  | [2023-03-24 13:01:46.358] ERR net.cc:318 Couldn't bind port 51413 on 10.2.0.2: Address not available (99) (net.cc:318)
transmission-1  | setsockopt IP_MULTICAST_IF: Address not available
transmission-1  | bind: Address not available
```

**Comment by fetzu** [comment]
Hey @PHLAK, I have been struggling with the same issue today. In my case, it was due to "bind-address-ipv4" being set to an IP in my settings.json.

Try changing the "bind-address-ipv4" to "0.0.0.0" ("bind-address-ipv4": "0.0.0.0",) in the settings.json and restart the docker container. Hope this helps !

**Comment by firasdib** [comment]
I second this. I've tried everything, cannot get any meaningful logs out of this container at all, and the maintainers seem reluctant to add the necessary parameters to the container.

**Comment by drizuid** [comment]
I am a bit confused about the issue. If i am message-level 1 i don't get much, if i set to message-level 2, i get spammed to hell with updates. In the case of PHLAK, i wouldn't expect any logs beyond what is there because the container doesn't look like it's running correctly due to some host side conflicts with the container.

fireasdib claims some necessary parameters are missing but provides no useful information or pull requests to add these "necessary parameters." Without someone reproducing this issue in a working setup and providing the relevant information, there is simply nothing we can do. We are not reluctant to do anything aside from make wild guesses that would impact the hundreds of thousands of users we have to MAYBE fix a problem that is most likely only on the user's end.

That said, I am happy to be proven wrong if one of you wants to step up and actually do some work in providing meaningful info.

**Comment by firasdib** [comment]
@drizuid No matter what message level I use, I get nothing (only what you see in the original post by @PHLAK). If I use level 3, I get some odd warnings here and there, but nothing else. The output is very lacking.

If I modify the docker files and re-launch the process with `--log-info --logfile /config/transmission.log` I start getting all the useful information I needed in the log file.

What I would love is for this to be included by default in the image. I've searched the issues for this problem, and it seems very common. If there is anything I can do on my end to troubleshoot why its happening, please tell me.

**Comment by drizuid** [comment]
Unless we can reproduce this issue (we can't) or someone shows us the code causing the purported issue and the subsequent fix, there is nothing we can do. Much as I hate to say this, it's working fine for us and it would be silly for us to push a change for one user. The op's container has other issues caused by their host so they do not factor in.

**Comment by firasdib** [comment]
I'm confused what possible issued could be caused by their host? Can you show a snippet of the logs you see on your end?

**Comment by PHLAK** [comment]
> The op's container has other issues caused by their host so they do not factor in.

What other host issues are you referring to here?

I just tried to run a new container from a different host with the `docker-compose.yaml` file below and `"message-level": 2` in my `settings.json` file and am still not getting any informational messages.

```yaml
version: '3.4'

services:
  transmission:
    image: linuxserver/transmission
    environment:
      PUID: 1000
      PGID: 1000
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ./config:/config
    restart: unless-stopped
``` 

### Steps to Reproduce

  1. Created a new `docker-compose.yaml` file with the contents shown above
  2. Ran `docker compose up -d`
  3. Verified that `message-level` was set to `2` in the `config/settings.json` file that was created
  4. Run `docker compose logs --follow --tail 20 transmission`
  5. Added a torrent (specifically the Arch Linux ISO from the magnet link at https://archlinux.org/download/)
  6. Observed that no additional logs are being generated aside from the LSIO banner

**Comment by PHLAK** [comment]
For the record, according to the [Transmission docs](https://github.com/transmission/transmission/blob/main/docs/Editing-Configuration-Files.md#misc) log level `2` should show informational logs.

**Comment by drizuid** [comment]
The logs from the original OP clearly should a lack of binding due to a host port conflict. Either way, we are unable to reproduce any of these issues. I had a completely silent container log, i changed message-level to 2, i got spammed to hell with logs, set back to 1, nice and quiet. We can't fix what we can't reproduce.

that said, in the "steps to reproduce" shown above, that wouldn't work because that isn't how you modify the settings.json. As stated in the readme, you must stop the container to modify settings.json, so step 2 followed by 3 is a clear lack of following direction which WOULD result in the change not going into effect and thus, no change.

**Comment by drizuid** [comment]
OK sorry, am back, got distracted by diablo4.
here is a paste with the first half being message-level: 1, then message-level: 2

https://hastebin.com/share/wiqosatape.yaml

**Comment by firasdib** [comment]
Thank you for your detailed posts. 

My compose looks identical to yours, so I’m unsure what the issue could be on my end. Folder and file permissions all look fine. 

Jusging by your log sample, I’m not sure you’re getting the correct logs, either. It should write a lot more informational logs about what torrents you have, their status, etc etc. 

I can investigate this further next week when I’m back home.

**Comment by drizuid** [comment]
> It should write a lot more informational logs about what torrents you have, their status, etc etc.

I only ran for a couple seconds before I cancelled and changed logging back to 1. Perhaps it's not getting all the details, but it's getting individual torrent info from trackers which didn't happen on level 1. I'm down to assist once you're back home though.

**Comment by firasdib** [comment]
My logs look identical to OPs:

```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

ln: failed to create symbolic link '/transmissionic/index.html': File exists
ln: failed to create symbolic link '/combustion-release/index.html': File exists
ln: failed to create symbolic link '/flood-for-transmission/index.html': File exists
ln: failed to create symbolic link '/kettu/index.html': File exists
ln: failed to create symbolic link '/transmission-web-control/index.html': File exists
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

> lack of binding due to a host port conflict
What does this mean? How can I resolve this?

**Comment by PHLAK** [comment]
> in the "steps to reproduce" shown above, that wouldn't work because that isn't how you modify the settings.json. As stated in the readme, you must stop the container to modify settings.json, so step 2 followed by 3 is a clear lack of following direction which WOULD result in the change not going into effect and thus, no change.

I understand this procedure, however, when I said "verified that `message-level` was set to `2`" I meant that the `message-level` was set to `2` by default on container instantiation. Perhaps that's part of the problem? I'll try going through changing the level using the full procedure later and see if this makes a difference.

**Comment by firasdib** [comment]
> > lack of binding due to a host port conflict
> > What does this mean? How can I resolve this?
> 
> You dont have the error that OP showed in [#240 (comment)](https://github.com/linuxserver/docker-transmission/issues/240#issuecomment-1483352301) though yours definitely looks like mine did on level 1.

Right, this is what I have in my `settings.json`:

```
cat /docker/torrent-tools/transmission/config/settings.json | grep 'message-level'
    "message-level": 2,
```

And I have verified this is the correct `settings.json` since if I stop the container, remove it, and start again, a new one is created in its place. And even with that one, I get no logs.

**Comment by drizuid** [comment]
I am travelling until friday, when i get home ill spin up something on a different box and see what happens.

**Comment by geeooff** [comment]
Same problem here, no log produced.
I don't know if this matters but I'm using Podman, not Docker Engine, on Ubuntu 22.04.02 LTS.

**Comment by PHLAK** [comment]
> I'll try going through changing the level using the full procedure later and see if this makes a difference.

Tried and still no longs. :confused:

**Comment by drizuid** [comment]
ill engage the team and see if anyone has ideas.

**Comment by sbrudenell** [comment]
Just encountered this and I think the issue is transmission's docs are out of date.

[Docs](https://github.com/transmission/transmission/blob/4.0.3/docs/Editing-Configuration-Files.md) say:
> message-level: Number (0 = None, 1 = Error, 2 = Info, 3 = Debug, default = 2) Set verbosity of Transmission's log messages.

But [the header file](https://github.com/transmission/transmission/blob/4.0.3/libtransmission/log.h#L16-L41) implies different values:
```c++
enum tr_log_level
{
    // No logging at all
    TR_LOG_OFF,

    // Errors that prevent Transmission from running
    TR_LOG_CRITICAL,

    // Errors that could prevent a single torrent from running, e.g. missing
    // files or a private torrent's tracker responding "unregistered torrent"
    TR_LOG_ERROR,

    // Smaller errors that don't stop the overall system,
    // e.g. unable to preallocate a file, or unable to connect to a tracker
    // when other trackers are available
    TR_LOG_WARN,

    // User-visible info, e.g. "torrent completed" or "running script"
    TR_LOG_INFO,

    // Debug messages
    TR_LOG_DEBUG,

    // High-volume debug messages, e.g. tracing peer protocol messages
    TR_LOG_TRACE
};
```

I used `"message-level": 4,` and now I get info messages.

**Comment by PHLAK** [comment]
> I think the issue is transmission's docs are out of date

OH MY GOD! That was it! Changing `message-level` to `4` showed informational logs!

So that means the following values for `message-level` should be

  - `0`: Off (no logs)
  - `1`: Critical
  - `2`: Errors
  - `3`: Warnings
  - `4`: Informational
  - `5`: Debugging
  - `6`: Trace

I will PR this change to the docs.

**Comment by drizuid** [comment]
Great effort guys, thanks a bunch to @PHLAK and @sbrudenell for submitting the PR and figuring out the issue! I was seeing so much data at 2 (the logs showed errors and this makes more sense now) that I couldn't wrap my head around there possibly being MORE data than that!
