### ISSUE TITLE
[FEAT] Document Supported WebUIs

### ISSUE THREAD

**Issue by Sanrax** [linuxserver/docker-transmission#257]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

The documentation in the readme currently doesn't list what webUIs are available inside the container to set. The documentation tells you about Transmission web home parameter, but not what values are supported.

I literally had to exec into the container to look at the folders in the root to find out what WebUIs were baked into the container.

### Reason for change

Better documentation needed.

**Comment by Sanrax** [comment]
Looks like you removed them, lol. I guess that makes more sense then. Dumb decision though, IMO.

**Comment by aptalca** [comment]
Thank you for your insightful comment and unsolicited opinion. They are available as mods, which are linked in the readme: https://mods.linuxserver.io/?mod=transmission

**Comment by Sanrax** [comment]
> Thank you for your insightful comment and unsolicited opinion. They are available as mods, which are linked in the readme: https://mods.linuxserver.io/?mod=transmission

Cool, I guess I'll try that then. Thanks.
