### ISSUE TITLE
[BUG] Incomplete folder

### ISSUE THREAD

**Issue by barukh27** [linuxserver/docker-transmission#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you download a file a folder "incomplete" is created. The same happens with a folder "complete".

### Expected Behavior

It would be better to have a volume (`/hostpathtoincomplete)` to bind the folder (`/incomplete`).

### Steps To Reproduce

Volumes created as docker-compose template.

### CPU architecture

arm64

### Docker creation

```bash
volumes:
      - /path/to/data:/config
      - /path/to/downloads:/downloads
      - /path/to/watch/folder:/watch
```

### Container logs

```bash
-
```

**Comment by aptalca** [comment]
You can bind mount any path you like as long as it doesn't interfere with a path the container manages

**Comment by barukh27** [comment]
> You can bind mount any path you like as long as it doesn't interfere with a path the container manages

Thank you for your reply.

So, if I bind `/mnt/incompletes` to `/incomple` it should work. 

I have another question, the folder "complete" and "downloads" is the same. If not, how is it that the folder "complete" is created?
