### ISSUE TITLE
[BUG] stats.json isn't written when stopping the container

### ISSUE THREAD

**Issue by Metal-Snake** [linuxserver/docker-transmission#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

transmission and the container stops without writing the stats.json file. Losing the active time stats since last write to the file (usually when finishing a torrent)

### Expected Behavior

It should write the stats.json file, so that the total active time is updated.

### Steps To Reproduce

1. start the container
2. just wait a few minutes without finishing or adding torrents
3. check total active time
4. stop the container
5. start the container
6. check total active time (now it's less than before)

### Environment

```markdown
- OS: DSM 7.2
- How docker service was installed: DSM Container Manager
```

### CPU architecture

x86-64

### Docker creation

<img width="1220" alt="Bildschirmfoto 2023-11-01 um 18 51 51" src="https://github.com/linuxserver/docker-transmission/assets/898220/4fbf692f-eace-4232-bb65-5ce11987fa65">
<img width="665" alt="Bildschirmfoto 2023-11-01 um 18 52 05" src="https://github.com/linuxserver/docker-transmission/assets/898220/6a6d3491-ee0b-4bac-841d-d1901f88c770">

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1026
User GID:    100
───────────────────────────────────────

ln: failed to create symbolic link '/transmissionic/index.html': File exists
ln: failed to create symbolic link '/combustion-release/index.html': File exists
ln: failed to create symbolic link '/flood-for-transmission/index.html': File exists
ln: failed to create symbolic link '/kettu/index.html': File exists
ln: failed to create symbolic link '/transmission-web-control/index.html': File exists
[custom-init] No custom files found, skipping...
crond[159]: crond (busybox 1.36.0) started, log level 5
[ls.io-init] done.
crond[159]: USER root pid 201 cmd run-parts /etc/periodic/15min
```

**Comment by smeretech** [comment]
Hello
Just tested with latest version and the system not open the ports to the docker:

`root@0d38ccc66b68:/# netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 127.0.0.11:42559        0.0.0.0:*               LISTEN
udp        0      0 0.0.0.0:8472            0.0.0.0:*
udp        0      0 127.0.0.11:58998        0.0.0.0:*
`
I tried with the repository version 4.0.3 and all it worked.

`root@53e745cad67d:/# netstat -an | more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.11:40164        0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN`

![image](https://github.com/linuxserver/docker-transmission/assets/18097022/5b57ccc7-2381-44d4-80f6-f94f0ed0e12d)

**Comment by j0nnymoe** [comment]
@smeretech don't know how this is related to the OP issue. Please open a new thread.

**Comment by Metal-Snake** [comment]
activity bump

**Comment by KuraiAndras** [comment]
Bumping, I have the same issue. Is this realted to https://github.com/transmission/transmission/issues/870 ?

**Comment by Metal-Snake** [comment]
activity bump

**Comment by Metal-Snake** [comment]
activity bump

**Comment by homerr** [comment]
Can confirm I have reproduced this, I will look into what is causing it and if we can fix it. It may be related to issue 870 on transmission

**Comment by homerr** [comment]
Unfortunately, I have bad news. I've tried this two different ways;

Running up an Alpine based VM and installing Transmission from apk (effectively how our container works) exhibited the same behaviour.

Compiling from source on a Debian machine, also exhibited the same behaviour.

It seems that the issue referenced above could be to do with this, but there is certainly something broken upstream.

I'd recommend reporting it to the transmission team hopefully they will be able to resolve the bug in their app.

Sorry to not have better news!

**Comment by Metal-Snake** [comment]
Thank you for looking into it!
