### ISSUE TITLE
[FEAT] Delete images with date tags (2021.11.18, 2021.10.28, 2021.10.21 and 2021.10.07)

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [linuxserver/docker-transmission#264]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Delete the next tags from GitHub and docker hub registries:

* `2021.11.18`
* `2021.10.28`
* `2021.10.21`
* `2021.10.07`

I don't know why that ever exists, others, and this image don't use date tags. Tags in this format appear only 4 times and aren't used in such form nor before or after.

### Reason for change

Those tags look like SemVer tags, so, that confuses [Mend Renovate](https://github.com/apps/renovate) bot that I use to keep my images up-to-date.

![image](https://github.com/linuxserver/docker-transmission/assets/20245745/367f3ac1-f8aa-4a4d-af47-8bc3539cb40e)

**Comment by Roxedus** [comment]
We do not delete tags.

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#semver-info
