### ISSUE TITLE
[FEAT] Read complete/incomplete folder paths from docker env

### ISSUE THREAD

**Issue by cartfisk** [linuxserver/docker-transmission#265]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

As described in a [previous issue](https://github.com/linuxserver/docker-transmission/issues/256) this container automatically creates `complete` and `incomplete` folders within `downloads`. If a user has custom/legacy paths for their complete/incomplete directories, these folders reappear every time the container restarts. I would like to be able to have some control over this behavior.

### Reason for change

I recently migrated a large (~2000 xfers) transmission environment from Ubuntu to this container. My existing completed download directory is named `completed` and I would like to continue using that name without the `complete` dir interfering with my tab complete. The process of rewriting transmission's `.resume` files to match the `complete` naming convention is tedious and prone to errors.

### Proposed code change

Maybe the [mkdir](https://github.com/linuxserver/docker-transmission/blob/3a1ad52e2356c5f0b5576239199475a671dd2ceb/root/etc/s6-overlay/s6-rc.d/init-transmission-config/run#L4-L6) and [lsiown](https://github.com/linuxserver/docker-transmission/blob/3a1ad52e2356c5f0b5576239199475a671dd2ceb/root/etc/s6-overlay/s6-rc.d/init-transmission-config/run#L56-L62) commands in the init script & the default `settings.json` could read these paths from the docker env?

**Comment by jcasale** [comment]
I would find this very useful as well.
