### ISSUE TITLE
[BUG]  Custom crontabs no longer work

### ISSUE THREAD

**Issue by havardAasen** [linuxserver/docker-transmission#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Custom crontab is no longer working within the container.

### Expected Behavior

Previously I had the file `config/crontab/root` with my custom settings, this was copied to `/etc/crontab/root` inside the container.

### Steps To Reproduce

Create the file in `config/crontab/root`, with the version prior to #254 this gets copied into, and is used, in the container, in later version, this file is ignored.

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: apt
```

### CPU architecture

x86-64

### Docker creation

```bash
.
```

### Container logs

```bash
.
```

**Comment by havardAasen** [comment]
Missing feedback from maintainer, still a valid issue.

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2023-11-02-cron/

**Comment by havardAasen** [comment]
> https://info.linuxserver.io/issues/2023-11-02-cron/

Thanks, seems to the info I needed.

Why is nothing mentioned in the changelog, a notice that the functionality was going away and that link? After all, that's what the changelog is for.

**Comment by aptalca** [comment]
It was a change at the baseimage level. Not specific to this image.
