### ISSUE TITLE
[BUG] Building manually results in errors in the container

### ISSUE THREAD

**Issue by jeromecst** [linuxserver/docker-transmission#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Container not starting because of many errors

### Expected Behavior

Container correctly starting the daemon

### Steps To Reproduce

1. Manually build the image with `docker build --no-cache --pull -t transmission_local .`
2. Run the compose file with `docker compose up`

### Environment

```markdown
- OS: Arch Linux 6.6.8
- How docker service was installed: pacman
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  transmission:
    image: transmission_local
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
```

### Container logs

```bash
https://pastebin.com/3CLqFq7Z
```

**Comment by homerr** [comment]
I've just built this locally on both a macOS and Debian environment with no issues at build time or run time. I'm afraid the issue will be with your local configuration.
