### ISSUE TITLE
[FEAT] Frequent releases / Understand releases changes

### ISSUE THREAD

**Issue by onjour** [linuxserver/docker-transmission#274]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Sorry I'm not a developer and I merely managed to make Docker work. Thank you for your awesome work.

I'm struggling to understand something: why is there so many releases of the docker image? 

For instance, what's the difference between https://github.com/linuxserver/docker-transmission/releases/tag/4.0.5-r0-ls211 through https://github.com/linuxserver/docker-transmission/releases/tag/4.0.5-r0-ls222? The changelog is the same and I cannot find any further information.   

Is there some information missing in the changelog? 

### Reason for change

More understandable release schedule / update policy.

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-transmission/compare/4.0.5-r0-ls211...4.0.5-r0-ls222

The changelog does not include OS package updates or backend CI changes, but they are all recorded in the repo commit history.

**Comment by onjour** [comment]
Thanks @thespad I didn't know about this and I understand better now, from a user standpoint, would you say that it makes sense to update at each new release?

**Comment by thespad** [comment]
It makes sense to update regularly - weekly is fine, more frequently if you prefer - but don't obsess over staying up to date with every image we release as depending on a number of different factors we can end up publishing multiple builds a day.

Obviously if there's an upstream update you want/need or something security related then you should update immediately.

**Comment by onjour** [comment]
Thanks @thespad you've been very helpful. Sorry for hijacking the issue(s) section, but I don't have Discord and didn't find a way to reach out otherwise! I'll know what to do now, cheers!
