### ISSUE TITLE
[FEAT] .torrent files

### ISSUE THREAD

**Issue by nurbat** [linuxserver/docker-transmission#275]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

1. Possibility to enable - That when you start downloading from /watch folder, it would not be renamed, but moved from /watch/my.torrent folder to /torrent_complete/my.torrent folder (When you finish downloading the file, the .torrent file would be moved to another folder).
2. Ability to enable - Automatic deletion of downloaded .torrent files (When the file download is complete, the .torrent file is deleted)
3. Ability to enable - Automatic deletion of torrent downloads, from the interface. (So that when the file download is completed, it would disappear from the interface).

### Reason for change

no comments

**Comment by Roxedus** [comment]
English please.

**Comment by nurbat** [comment]
1. Possibility to enable - That when you start downloading from /watch folder, it would not be renamed, but moved from /watch/my.torrent folder to /torrent_complete/my.torrent folder (When you finish downloading the file, the .torrent file would be moved to another folder).
2. Ability to enable - Automatic deletion of downloaded .torrent files (When the file download is complete, the .torrent file is deleted)
3. Ability to enable - Automatic deletion of torrent downloads, from the interface. (So that when the file download is completed, it would disappear from the interface).

**Comment by j0nnymoe** [comment]
Wouldn't this be a feature request to transmission and not us? We just package what they release.

**Comment by nurbat** [comment]
I apologize, for some reason I thought you developed this application, again I apologize. Can you tell me where I can address with this proposal?

**Comment by j0nnymoe** [comment]
https://transmissionbt.com/
