### ISSUE TITLE
[FEAT] Add Unflac Mod?

### ISSUE THREAD

**Issue by JohnGalt1717** [linuxserver/docker-transmission#283]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like there to be a docker mod that would install Unflac automatically.  https://github.com/nilzeronull/unflac

### Reason for change

This would allow using a script on torrent completion to split apart single flac audio using the cue sheet into separate audio tracks.

### Proposed code change

Create a docker mod that installs unflac in the container for transmission.

**Comment by j0nnymoe** [comment]
If you're willing to create the mod, we will accept it into the mod repo.

**Comment by JohnGalt1717** [comment]
Haven't a clue how to do so. Is there docs for creating mods that do similar?

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-mods/

But also it's a static go binary so you could probably just mount it straight into the container

**Comment by JohnGalt1717** [comment]
it's:

apk add ffmpeg go
go install git.sr.ht/~ft/unflac@latest


Then it's available at: ~/go/bin/unflac



Are you saying just compile the thing and then put it in a folder that is accessible and update the script to use it?

**Comment by j0nnymoe** [comment]
You can just use the package installer mod to install it.
