### ISSUE TITLE
[BUG] tail: invalid PID ''

### ISSUE THREAD

**Issue by MorganMLGman** [linuxserver/docker-transmission#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Transmission is constantly printing `tail: invalid PID ''` in logs. Transmission not working.

### Expected Behavior

Transmission should start noramlly.

### Steps To Reproduce

1. Pull 4.0.6-r0-ls249
2. Start transmission container.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission

    restart: unless-stopped
    networks:
      default:

    ports:
      - 51413:51413/tcp
      - 51413:51413/udp
      - 9091:9091   

    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - WHITELIST=192.168.*.*,172.18.*.*

    volumes:
      - $DOCKER_APPS_DIR/transmission:/config
      - $HDD_RAID/downloads:/downloads
```

### Container logs

```bash
In comment
```

**Comment by MorganMLGman** [comment]
![image](https://github.com/user-attachments/assets/1c23baa4-adc5-445e-b477-2803f1da8ad0)

after going back to 4.0.6-r0-ls248

![image](https://github.com/user-attachments/assets/d60ef276-464a-4dbd-adcd-9b98ccc03081)

**Comment by j0nnymoe** [comment]
It's an upstream bug.

**Comment by Roxedus** [comment]
https://github.com/transmission/transmission/issues/7035

**Comment by gkalemis** [comment]
In my case all the torrents reset every sometime (one minute or less) and start downloading from the beginning. If I limit the queue to 1 torrent, then it is working as it should.

**Comment by dansaman** [comment]
Same issue here. Limiting the queue to 1 is my workaround.

**Comment by Roxedus** [comment]
This is a know issue. please refrain from "+1" or "me to" comments. You can use the Notification settings for this issue to subscribe to issues.

**Comment by kiritoxjf** [comment]
```
2024-08-08 21:33:50.123834+08:00./run: line 8:  1148 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
2024-08-08 21:33:53.730838+08:00s6-supervise svc-transmission: warning: finish script lifetime reached maximum value - sending it a SIGKILL
2024-08-08 21:33:54.974674+08:00Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
2024-08-08 21:39:20.059942+08:00./run: line 8:  1165 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
2024-08-08 21:39:20.869279+08:00tail: invalid PID: ‘’
2024-08-08 21:39:21.981593+08:00Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
2024-08-08 21:40:42.672000+08:00./run: line 8:  1182 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
2024-08-08 21:40:44.208640+08:00tail: invalid PID: ‘’
2024-08-08 21:40:45.364969+08:00Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
2024-08-08 21:41:58.371304+08:00./run: line 8:  1199 Killed                  s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-9091}" s6-setuidgid abc /usr/bin/transmission-daemon -g /config -f
2024-08-08 21:42:01.788674+08:00tail: invalid PID: ‘’
2024-08-08 21:42:03.078050+08:00Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
```
I got the same error. Hoping for solving.

**Comment by corzocone** [comment]
> Would it not make more sense to just revert the automatic package updates made by the bot in [a1a8556](https://github.com/linuxserver/docker-transmission/commit/a1a8556f2815a5f378e30cbfb0376eecb9517802)? Latest and 4.0.6 tags both point to a broken build because it contains curl & libcurl 8.9.1. Just because it's a known upstream issue doesn't mean it needs to remain a downstream issue until either curl or Transmission update again to fix it, 4.0.6-r0-ls248 containing 8.9.0 works fine.

You're not wrong, but HDB (as an example) has banned all instances of 4.0.6. I've had to downgrade to the latest 4.0.5 to remain active on that tracker.

**Comment by j0nnymoe** [comment]
Best practice is to not run the latest tag, specially if you're using it with something that requires a specific version.

**Comment by thespad** [comment]
The short answer is we cannot "revert" minor package updates with Alpine-based images, but that's the whole point of tagging every release, so that users can pick any available combination of versions in the event that something causes an incompatibility somewhere that we can't work around.

Major package updates are another matter but that's not a factor here.

**Comment by ivanjx** [comment]
maybe there should be a "stable" tag or make "latest" to be "stable" and add a new "nightly" tag to update to latest as fast as possible

**Comment by ivanjx** [comment]
also the fix seems to be shipped already https://git.alpinelinux.org/aports/commit/?id=aeebff52d27fbce44e3db76e8c0dabee15e649fa

**Comment by baskinsy** [comment]
Running fine for 30 minutes now for me. Thanks!

**Comment by SunRed** [comment]
Issue seems to be resolved for me as well. Thanks.

**Comment by phoenixtechnam** [comment]
Im having that issue for months now, although I install the latest versions this image is completely unusable to me now.

```
[2024-12-19 20:47:26.951] utils.cc:129: Couldn't read '/config/settings.json': Permission denied (13)
[2024-12-19 20:47:26.951] ERR transmission-daemon Error loading config file -- exiting. 
```

On every restart, it re-writes the config file with completely empty permissions and then fails to read the file.
Same hap[ens to bandwidth-groups.json, dht.dat, stats.json.
Manually fixing the permissions works until next time the container is restarted

**Comment by j0nnymoe** [comment]
Open a new thread and provide details requested.

**Comment by kiritoxjf** [comment]
> Im having that issue for months now, although I install the latest versions this image became completely unusable to me.
> 
> ```
> [2024-12-19 20:47:26.951] utils.cc:129: Couldn't read '/config/settings.json': Permission denied (13)
> [2024-12-19 20:47:26.951] ERR transmission-daemon Error loading config file -- exiting. 
> invalid PID ''
> ```
> 
> On every restart, it re-writes the config file with completely empty permissions and then fails to open the file. Same hapens to bandwidth-groups.json, dht.dat, stats.json. Manually fixing the permissions works until next time the container is restarted

According to your log msg, it may caused by the limits of authority. It may works after you set the PUID environment variable to the docker contrainer.
