### ISSUE TITLE
[FEAT] Add option to disable µtp

### ISSUE THREAD

**Issue by Chaz6** [linuxserver/docker-transmission#290]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would like an env var to disable µtp (the equivalent of `{ "utp-enabled": false }` in `settings.json`).

### Reason for change

My access to the internet is through an isp-provided cable modem which uses the intel puma chipset, which has a nasty bug affecting protocols other than tcp or udp. When µtp is enabled it causes the modem to have a fit and causes massive packet loss.

See also https://www.ispreview.co.uk/index.php/2018/08/intel-coughs-to-puma-cpu-flaw-that-hit-virgin-media-hub-3-router.html

**Comment by aptalca** [comment]
No need for an env var. Just edit the settings file

**Comment by Roxedus** [comment]
or https://github.com/linuxserver/docker-mods/tree/transmission-env-var-settings if you really need it as an env
