### ISSUE TITLE
[FEAT] Add Python3-requests

### ISSUE THREAD

**Issue by nyxs** [linuxserver/docker-transmission#291]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Please consider the py3-requests to the Dockerfile, so we will be able to use Python to handle HTTP requests

### Reason for change

We will be able to do more with Python inside Transmission docker

### Proposed code change

echo "**** install packages ****" && \
  apk add --no-cache \
    findutils \
    p7zip \
    python3 \
    **py3-requests && \**

**Comment by Roxedus** [comment]
you can use the universal install mod https://github.com/linuxserver/docker-mods/tree/universal-package-install
