### ISSUE TITLE
[BUG] After update from 4.0.6-r0-ls265 to 4.0.6-r0-ls266 not starting

### ISSUE THREAD

**Issue by abubaca4** [linuxserver/docker-transmission#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not start with error
`ERR transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-4.0.6/daemon/daemon.cc:914)
tail: invalid PID: ‘’`

### Steps To Reproduce

Just start container

For me falied after update by watchtower

Manual start also failed

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: from debian repo
```

### CPU architecture

arm64

### Docker creation

```bash
docker run --name "transmission" --volume "/mnt/MG04ACA400N:/mnt/MG04ACA400N" --volume "/mnt/MG04ACA400N/torrents/Transmissionic:/web" --volume "/mnt/MG04ACA400N/torrents/transmission_data:/config" --restart "always" --network "host" --env "UMASK=000" --env "PUID=1000" --env "PGID=1000" --env "TRANSMISSION_WEB_HOME=/web" --env "USER=admin" --env "PASS=*************" --detach lscr.io/linuxserver/transmission:latest
```

### Container logs

```bash
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────
Linuxserver.io version: 4.0.6-r0-ls266
Build-date: 2024-11-13T12:53:01+00:00
───────────────────────────────────────

ln: failed to create symbolic link '/transmissionic/index.html': File exists
ln: failed to create symbolic link '/combustion-release/index.html': File exists
ln: failed to create symbolic link '/flood-for-transmission/index.html': File exists
ln: failed to create symbolic link '/kettu/index.html': File exists
ln: failed to create symbolic link '/transmission-web-control/index.html': File exists
[custom-init] No custom files found, skipping...
[2024-11-13 18:39:58.921] ERR transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-4.0.6/daemon/daemon.cc:914)
tail: invalid PID: ‘’
[2024-11-13 18:40:00.198] ERR transmission-daemon Error loading config file -- exiting. (/home/buildozer/aports/community/transmission/src/transmission-4.0.6/daemon/daemon.cc:914)
tail: invalid PID: ‘’
```

**Comment by Deagarys** [comment]
Can confirm same issue, after i just updated.

**Comment by Baine** [comment]
seems like the way the UMASK is handled has changed
had to encapsulate the value in quotes (UMASK="022") and the config file could get parsed again

**Comment by uhop** [comment]
That change was my PR, which didn't account for unquoted `umask`. I submitted the PR that does it: #293.

**Comment by uhop** [comment]
The temporary fix for now is to use a quoted value for `umask`: `UMASK="022"`. Thx, @Baine.

**Comment by abubaca4** [comment]
> seems like the way the UMASK is handled has changed had to encapsulate the value in quotes (UMASK="022") and the config file could get parsed again in the settings file this is what it looks like now
> 
> ```json
>     "umask": "022",
> ```

For me
Change -e UMASK=000 to -e UMASK="000" not help
Change "umask": 000 in file to "umask": "000" and -e UMASK=000 to -e UMASK="000" not help
Remove "umask": 000 from file and -e UMASK=000 from comand line help for me(but umask now 022). I changed it many time ago because I has some problem with run executable files in samba share.

**Comment by uhop** [comment]
@abubaca4 It looks like you use the command line to start the container. In this case, try escaping quotes to avoid `sh` eating them: `-e UMASK=\"000\"`.

**Comment by nemchik** [comment]
@uhop @abubaca4 this could use a test if you're willing to try the tag https://github.com/linuxserver/docker-transmission/pull/294#issuecomment-2475116238
`linuxserver/lspipepr-transmission:4.0.6-r0-pkg-b6d4b051-dev-4ca680899ef161b1cf5503df832776a57e2db15e-pr-294`

**Comment by abubaca4** [comment]
> @uhop @abubaca4 this could use a test if you're willing to try the tag [#294 (comment)](https://github.com/linuxserver/docker-transmission/pull/294#issuecomment-2475116238) `linuxserver/lspipepr-transmission:4.0.6-r0-pkg-b6d4b051-dev-4ca680899ef161b1cf5503df832776a57e2db15e-pr-294`

ls267 work thanks

**Comment by nemchik** [comment]
> > @uhop @abubaca4 this could use a test if you're willing to try the tag [#294 (comment)](https://github.com/linuxserver/docker-transmission/pull/294#issuecomment-2475116238) `linuxserver/lspipepr-transmission:4.0.6-r0-pkg-b6d4b051-dev-4ca680899ef161b1cf5503df832776a57e2db15e-pr-294`
> 
> ls267 work thanks

That's good news, but the image:tag I just posted are different and need testing before merging in to create another new release. The changes in the new test image should be more resilient long term.

**Comment by abubaca4** [comment]
> > > @uhop @abubaca4 this could use a test if you're willing to try the tag [#294 (comment)](https://github.com/linuxserver/docker-transmission/pull/294#issuecomment-2475116238) `linuxserver/lspipepr-transmission:4.0.6-r0-pkg-b6d4b051-dev-4ca680899ef161b1cf5503df832776a57e2db15e-pr-294`
> > 
> > 
> > ls267 work thanks
> 
> That's good news, but the image:tag I just posted are different and need testing before merging in to create another new release. The changes in the new test image should be more resilient long term.

linuxserver/lspipepr-transmission:4.0.6-r0-pkg-b6d4b051-dev-4ca680899ef161b1cf5503df832776a57e2db15e-pr-294 also work
