### ISSUE TITLE
[BUG] Completed torrents written with readonly permissions

### ISSUE THREAD

**Issue by thany** [linuxserver/docker-transmission#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Once a torrent is completed, it is moved to its final location on disk, and that location is created using `drwxr-xr-x` permission. This prevents me from being able to delete it.

### Expected Behavior

It should inherit permissions from the parent directory, i.e. not touch permissions at all and just let the filesystem decide. For me that would be `drwxrwxrwx` on the parent directory.

### Steps To Reproduce

Just make sure the incomplete and complete directories are two physically distinct directories.

### Environment

```markdown
- OS: Unraid 6.12.13
- How docker service was installed: via "Apps"
```

### CPU architecture

x86-64

### Docker creation

![image](https://github.com/user-attachments/assets/72d2bce1-222e-417b-81d1-8b206294f8f4)

### Container logs

```bash
Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────
Linuxserver.io version: 4.0.6-r0-ls267
Build-date: 2024-11-14T00:18:40+00:00
───────────────────────────────────────
    
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
```

**Comment by BeeLazy** [comment]
Try pressing 'Show more settings...'. and change UMASK from 022 to 000

**Comment by thany** [comment]
I tried it and it works. But I have to mention that this issue has started showing itself out of nothing. All I've never done, is update the docker to its latest version ocassionally. I haven't touched any configuration, so I wonder why I should now.

And even if this is *the* solution, it would only solve it for me. Everybody else may still run into this problem. Shouldn't it be the default? I wonder what the thought process is behind this UMASK thing.

**Comment by BeeLazy** [comment]
Umask is what transmission use to handle file mode creation mask, and their default is 022, so it is a reasonable default to use on this container. Ref https://github.com/transmission/transmission/blob/main/docs/Editing-Configuration-Files.md#files-and-locations and https://man7.org/linux/man-pages/man2/umask.2.html

I do agree that 000 would be a better default value for the Unraid app.

**Comment by drizuid** [comment]
`000` give EVERYONE all access, we would never make 000 a default. It is better for users to understand how permissions and ownership work and set things properly. If a user WANTS to give everyone all access, that is their decision to make, not ours. 

that said, the file was not written with read only permissions, uid 99 has full access and the group and everyone have read access, which is very typical.  

Anyway, the OP has the solution which is also covered in our container readme, this is not a container issue. I will close this
