### ISSUE TITLE
[BUG] Peerport is being reset to 51413

### ISSUE THREAD

**Issue by RA341** [linuxserver/docker-transmission#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Updated transmission yesterday to cc489ce02927e526f1cba573b42d31a8cac66338aadcacc4b0d998341818d620, it seems it is resetting my torrent port to 51413 on restart, 

### Expected Behavior

The port in the env should be used 

### Steps To Reproduce

1. Start latest transmission, 
2. use the peerport env in the compose file
3. Open transmission webgui and check the port in settings
4. It should be different
 

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
transmissionprivate:
    container_name: transmissionpriv
    image: lscr.io/linuxserver/transmission:latest
    env_file:
      - env/tpriv.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${appdata_ssd}/transmissionpriv/config:/config
      - ${media}:/media
    ports:
      - "9092:9091"
      - "9888:9888"
    restart: unless-stopped

------------------------------------
Envfile

USER=...
PASS=...
PEERPORT=9888
```

### Container logs

```bash
ln: failed to create symbolic link '/transmissionic/index.html': File exists

ln: failed to create symbolic link '/combustion-release/index.html': File exists

ln: failed to create symbolic link '/flood-for-transmission/index.html': File exists

ln: failed to create symbolic link '/kettu/index.html': File exists

ln: failed to create symbolic link '/transmission-web-control/index.html': File exists

[custom-init] No custom files found, skipping...

Connection to localhost (127.0.0.1) 9091 port [tcp/*] succeeded!

[ls.io-init] done.
```

**Comment by Banawoke** [comment]
Hi,

It is the same issue old issue her : https://github.com/linuxserver/docker-transmission/issues/239
You need to change the file settings.json in your case in this folder : "${appdata_ssd}/transmissionpriv/config" the line to change is this one "peer-port"

**Comment by RA341** [comment]
Tried it, didn't work, it overwrote the config again when the container restarted

**Comment by derekoharrow** [comment]
I'm having exactly the same issue. Docker compose file includes PEERPORT=51866. I stop transmission and change peerport in settings.json to 51866. Then recreate the transmission container and it starts on 51413 and the settings.json file is changed to 51413 too - thought I was going mad! Glad it's not just me.
After each creation of the container, I have to manually go into the GUI and set the port back.

**Comment by Lightjohn** [comment]
Seems I have this issue also, setting.json is getting overwritten everytime.

**Comment by j0nnymoe** [comment]
you need to edit the settings.json when the container is stopped.

**Comment by aptalca** [comment]
I can confirm the issue locally, but no idea what's causing it.

Our init does successfully modify the settings.conf with the PEERPORT from env var: https://github.com/linuxserver/docker-transmission/blob/master/root/etc/s6-overlay/s6-rc.d/init-transmission-config/run#L36

But when the transmission daemon starts, it somehow gets reverted.

**Comment by aptalca** [comment]
I'm blind, I missed the string vs int

We'll get a fix out

**Comment by aptalca** [comment]
Can you guys test this image and confirm?
`ghcr.io/linuxserver/lspipepr-transmission:4.0.6-r0-pkg-ab12cd8b-dev-e40526e7dac729463aee02e60a9f1564af0f76de-pr-297`

**Comment by RA341** [comment]
working for me thanks
