### ISSUE TITLE
Use single /download directory

### ISSUE THREAD

**Issue by maximnaidenov** [linuxserver/docker-transmission#34]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Would you agree to get rid of the /downloads/complete and /downloads/incomplete directories and stick to single /downloads directory by default ?. Having incomplete directory is excessive to rename-partial-files: true and requires manual coping to medial library.
Of course everyone could edit the settings manually but it would be nice to have it simple in default configuration.
If you agree, I could do a PR with necessary changes ?

**Comment by aptalca** [comment]
I haven't used transmission in a while but iirc, you don't have to use the incomplete downloads folder. When you add a new torrent it gives you an option. I personally didn't use it.

**Comment by sparklyballs** [comment]
as @aptalca says, you don't have to use the incomplete folder and you can change the setting yourself manually.

**Comment by maximnaidenov** [comment]
yes, I can change the settings.json manually but I could not get rid of those two errors:
chown: changing ownership of '/downloads/complete': Operation not permitted
chown: changing ownership of '/downloads/incomplete': Operation not permitted
that happen because I do not have such directories.

**Comment by aptalca** [comment]
The container automatically creates those directories. How do you not have them?

Did you map a folder for `/downloads` ?
