### ISSUE TITLE
config overwritten settings.json

### ISSUE THREAD

**Issue by lemosm** [linuxserver/docker-transmission#37]
using the following setup:

docker run -d \
    --name=transmission \
    -v //f/docker/transmission/config:/config \
    -v //f/docker/transmission/downloads:/transmission/downloads \
    -v //f/docker/transmission/watch:/watch \
    -e PGID=0 -e PUID=0 \
    --net container:openvpn-client \
    --health-cmd "curl --fail https://www.google.ca || exit 1" \
    --restart=always \
    linuxserver/transmission

it seems from time to time my settings.json in /config is overwritten with the default settings.json. As a temporary fix I have manually modified the /defaults/settings.json to contain my changes but there should be a better way of doing this. My suggestion would be changes to /config/settings.json should persist to /defaults/settings.json

I haven't located the root cause of the issue, the container is only ever stopped and started but the image is never deleted.

**Comment by sparklyballs** [comment]
we've not seen this with any other users so far, also i noticed you're running as root,  and using a network path ?
the problem could be one of permissions.

writing changes to the defaults copy is not an option because for them to be persistent it would have to be mounted externally and then you'd be back to square one permissions wise anyways.

**Comment by maxcountryman** [comment]
This consistently happens to me. I read in another post [someone else was having the same issue](https://saasbootstrap.com/a-complete-guide-to-setting-up-a-plex-home-media-server-with-automated-requests-downloads/).

Should this be reopened?

**Comment by aptalca** [comment]
`Should this be reopened?`

Not unless you properly qualify your results

**Comment by maxcountryman** [comment]
As I mentioned, it happens whenever I restart compose. Please also see the article I linked which describes the exact behavior I'm experiencing.

**Comment by aptalca** [comment]
As explained in the readme, you need to edit that file while the container is stopped.
