### ISSUE TITLE
Directory creation on startup

### ISSUE THREAD

**Issue by avluis** [linuxserver/docker-transmission#4]
Is it possible to modify the way the directories are created, or should I say, is it possible to not have them [hardcoded](https://github.com/linuxserver/docker-transmission/blob/master/init/30_set_config.sh#L3-L7).

I'm not very savy with Docker just yet, so I'll have to be told if it is at all possible.
Since the config file for Transmission can be edited at any time (transmission only saves when shutting down if I recall correctly), can `30_set_config.sh` be updated with those values?

The reason I bring this up, is that if you are not saving in the directory `complete`, then you'll be creating said directory any time the container is started.

My only workaround to this at the moment is a fork with those values set to my current environment, but I am looking for alternatives as well.

**Comment by zaggash** [comment]
you can specify the volumes on container startup like :

```
-v /your/local/complete/folder:/downloads/complete
-v /your/local/incomplete/folder:/downloads/incomplete
```

it is comething doable for you ?

**Comment by avluis** [comment]
Yes, that's no problem -- but this is unfortunately not enough.
I'm referring to the script that is bundled, which runs at startup: `30_set_config.sh`:

```bash
#!/bin/bash

mkdir -p /downloads/{complete,incomplete} /watch

[[ ! -f /config/settings.json ]] && cp /defaults/settings.json /config/settings.json

chown abc:abc /watch /config/settings.json /downloads /downloads/incomplete /downloads/complete
```

It won't matter how I set up my folders for Docker since this script will create the `complete` and `incomplete` folders in the `downloads` directory anyways.

**Comment by avluis** [comment]
It doesn't bother me, here is the question I had, again:
> Is it possible to modify the way the directories are created, or should I say, is it possible to not have them hardcoded.

**Comment by zaggash** [comment]
Nop it's not.
