### ISSUE TITLE
Transmission does not use "download-dir", default root folder instead

### ISSUE THREAD

**Issue by rlapray** [linuxserver/docker-transmission#51]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Host : Synology 918+

- I stop the container
- I update my settings.json to change incomplete-dir and download-dir (they are in my "Download" shared folder like this : "Downloads/done" and "Downloads/ongoing")
- My "Downloads" shared folder is empty.
- I start the container.
- Starting a torrent : the incomplete-dir is created with .part files in it. Everything is fine.
- When the download is finished, the download-dir is not created
- Instead, i see my downloaded files at the root of "Downloads" shared folder

Interrestingly, when i access the transmission web interface, the download-dir is correct ("/downloads/test/done")

In my config, the 2 paths are absolute.

Nothing wrong in my logs. Nothing to tell me there's a permission problem or anything...

I have another server (archlinux home made) i wished to replace with the synology with transmission installed, and the configuration is the same.

This is my configuration file for reference : 

```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": true,
    "blocklist-url": "...",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/downloads/done",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 2,
    "idle-seeding-limit": 1,
    "idle-seeding-limit-enabled": true,
    "incomplete-dir": "/downloads/ongoing",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 0,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 1,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "...",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "...",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 100,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 100,
    "speed-limit-up-enabled": false,
    "start-added-torrents": true,
    "trash-original-torrent-files": false,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/watch",
    "watch-dir-enabled": true
}

```

**Comment by sparklyballs** [comment]
use the default internal locations set by the docker and change the location they map to on the host (the right side of the -v switch)

this is how this docker works but by changing locations such as you have we have no way of knowing that your changes are the root cause of your issues

**Comment by rlapray** [comment]
Nevermind, the application sending download request to transmission was sending a specific directory to download to.

Nothing wrong with the docker.

Another day another PEBKAC. Sorry and thank you for your time.
