### ISSUE TITLE
Don't find settings.json on Synology

### ISSUE THREAD

**Issue by kestouf** [linuxserver/docker-transmission#58]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Docker on Synology

##  Thanks, team linuxserver.io

My problem is simple.
I would like to add a login / password to the transmission GUI but I can not find the settings.json file in /config.
I close the docker I go to /config, but nothing.
Can you give me the full path to the fihcier settings.json location on a synology?

Thx for your help

**Comment by niXta1** [comment]
If you set something like `-v /volume1/docker/transmission:/config` you should find it in there. On synology shares mounts on `volume1` (depending on your setup, of course).

**Comment by thelamer** [comment]
As @niXta1 said synology shares are under volume1 or volume2. In the future please hop on our discord to discuss support requests not directly related to bugs in the codebase here. 
https://discord.gg/YWrKVTn
