### ISSUE TITLE
transmission creates unused directories in /downloads

### ISSUE THREAD

**Issue by whezzel** [linuxserver/docker-transmission#59]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

_Host OS:_ 

`Centos 7 - 3.10.0-862.9.1.el7.x86_64`

_Docker run command:_ 

`docker run -d --name transmission --network bridge1 \`
`--restart unless-stopped -v /docker-data/transmission:/config \`
`-v /common/downloads:/downloads -v /common/downloads/.torrents:/watch \`
`-v /etc/localtime:/etc/localtime:ro -e PGID=1015 -e PUID=1015 \`
`-p 9091:9091 -p 51413:51413 -p 51413:51413/udp \`
`linuxserver/transmission:latest`

_Related logs:_ 

`[fix-attrs.d] applying ownership & permissions fixes...,`
`[fix-attrs.d] done.,`
`[cont-init.d] executing container initialization scripts...,`
`[cont-init.d] 10-adduser: executing... ,`
`usermod: no changes,`
`-------------------------------------,`
`          _           (),`
`         | |  ___   _    __,`
`         | | / __| | |  /  \ ,`
`         | | \__ \ | | | () |,`
`         |_| |___/ |_|  \__/,`
`Brought to you by linuxserver.io,`
`We gratefully accept donations at:,`
`https://www.linuxserver.io/donations/,`
`-------------------------------------,`
`GID/UID,`
`-------------------------------------,`
`User uid:    1015,`
`User gid:    1015,`
`-------------------------------------,`
`[cont-init.d] 10-adduser: exited 0.,`
`[cont-init.d] 20-config: executing... ,`
`[cont-init.d] 20-config: exited 0.,`
`[cont-init.d] done.,`
`[services.d] starting services,`
`[services.d] done.,`
`[2018-08-13 04:37:31.260] Transmission 2.94 (d8e60ee44f) started (session.c:740),`
`[2018-08-13 04:37:31.260] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971),`
`[2018-08-13 04:37:31.260] RPC Server Adding address to whitelist: 192.168.20.* (rpc-server.c:971),`
`[2018-08-13 04:37:31.260] RPC Server Adding address to whitelist: 172.20.0.* (rpc-server.c:971),`
`[2018-08-13 04:37:31.260] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213),`
`[2018-08-13 04:37:31.260] RPC Server Whitelist enabled (rpc-server.c:1217),`
`[2018-08-13 04:37:31.260] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84),`
`[2018-08-13 04:37:31.260] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89),`
`[2018-08-13 04:37:31.260] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95),`
`[2018-08-13 04:37:31.260] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100),`
`[2018-08-13 04:37:31.260] DHT Reusing old id (tr-dht.c:307),`
`[2018-08-13 04:37:31.260] DHT Bootstrapping from 58 IPv4 nodes (tr-dht.c:156),`
`[2018-08-13 04:37:31.260] Using settings from "/config" (daemon.c:528),`
`[2018-08-13 04:37:31.260] Saved "/config/settings.json" (variant.c:1266),`
`[2018-08-13 04:37:31.260] Watching "/watch" for new .torrent files (daemon.c:573),`
`[2018-08-13 04:37:31.260] Blocklist "blocklist.bin" contains 411416 entries (blocklist.c:100),`
`[2018-08-13 04:37:31.260] Loaded 1 torrents (session.c:2034),`
`[2018-08-13 04:37:31.260] Port Forwarding (NAT-PMP) initnatpmp succeeded (0) (natpmp.c:70),`
`[2018-08-13 04:37:31.260] Port Forwarding (NAT-PMP) sendpublicaddressrequest succeeded (2) (natpmp.c:70),`
`[2018-08-13 04:37:39.258] Port Forwarding State changed from "Not forwarded" to "Starting" (port-forwarding.c:92),`
`[2018-08-13 04:37:39.258] Port Forwarding State changed from "Starting" to "???" (port-forwarding.c:92),`
`[2018-08-13 04:37:39.258] Changed open file limit from 1048576 to 1024 (fdlimit.c:380),`

_Symlinks:_ no symlinks used on the bind mount.

_Issue:_ This container creates unused directories in /downloads if you don't use default download/incomplete locations provided in settings.json. 

If I shutdown the container, then remove the unused directories from the persistent data stored on the host, when I start the container back up, it recreates the directories (/downloads/complete & /downloads/incomplete). Even though it is specified in the /config/settings.json to use /downloads/done and /downloads/in_progress. (attached is a copy of my settings.json - [settings.txt](https://github.com/linuxserver/docker-transmission/files/2282521/settings.txt))

This isn't a huge problem, I just like to keep my filesystem free of unused files/directories. I could always change my directories to use the defaults provided by this container but that would required rewriting scripts that I have running on other machines that also access this same network share.

**Comment by konachan700** [comment]
its really problem...

**Comment by thelamer** [comment]
Yeah the logic for that is here:

https://github.com/linuxserver/docker-transmission/blob/master/root/etc/cont-init.d/20-config#L4-L5

As it is just empty folders I do not see us even guarding this with if dir exists logic. 
Sorry to be so blunt, but either fork this and build local, or just deal with having these folders there.
