### ISSUE TITLE
Port always closed

### ISSUE THREAD

**Issue by thewinger** [linuxserver/docker-transmission#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
Host OS: Windows 10
Virtualbox in Bridge mode
Ubuntu 18.04 server

docker-compose code:
```
  transmission:
    image: "linuxserver/transmission"
    container_name: "transmission"
    ports:
      - "55650:9091"
      - "55651:51413"
      - "55651:51413/udp"
    volumes:
      - ${DOCKERDIR}/transmission:/config
      - ${DOCKERDIR}/shared:/shared
      - ${WATCHDIR}:/watch
      - ${DOWNLOADSDIR}:/downloads
    environment:
      - TZ= ${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
```

This is the log file from the last restart

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    999
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
usermod: no changes
[cont-init.d] 20-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2018-08-28 10:50:20.295] Transmission 2.94 (d8e60ee44f) started (session.c:740)
[2018-08-28 10:50:20.295] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
[2018-08-28 10:50:20.295] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
[2018-08-28 10:50:20.295] RPC Server Password required (rpc-server.c:1220)
[2018-08-28 10:50:20.295] Port Forwarding Stopped (port-forwarding.c:180)
[2018-08-28 10:50:20.295] DHT Reusing old id (tr-dht.c:307)
[2018-08-28 10:50:20.295] DHT Bootstrapping from 75 IPv4 nodes (tr-dht.c:156)
[2018-08-28 10:50:20.295] Using settings from "/config" (daemon.c:528)
[2018-08-28 10:50:20.295] Saved "/config/settings.json" (variant.c:1266)
[2018-08-28 10:50:20.295] transmission-daemon requiring authentication (daemon.c:554)
[2018-08-28 10:50:20.295] Watching "/watch" for new .torrent files (daemon.c:573)
[2018-08-28 10:50:20.295] Blocklist "blocklist.bin" contains 411571 entries (blocklist.c:100)
[2018-08-28 10:50:20.295] Loaded 10 torrents (session.c:2034)
[2018-08-28 10:50:20.295] Changed open file limit from 4096 to 1024 (fdlimit.c:380)
```

I have opened port 55651 in my router (both TCP and UDP). 
<img width="410" alt="screen shot 2018-08-28 at 12 57 31" src="https://user-images.githubusercontent.com/121455/44718970-296a2680-aac2-11e8-8350-4be7c6e321f1.png">

In settings.json I have the port 51413, and I can see that port in the settings window inside Transmission Web GUI, but it says "Port is closed".

What else do I need to do?

I also opened both ports (55651 and 51413 just in case) in Windows Defender Firewall.

**Comment by j0nnymoe** [comment]
I suspect it's something to do with virtualbox running in bridgemode, run it in NAT so it get's a dedicated IP from your DHCP and open the port to that IP instead.

**Comment by thewinger** [comment]
I think is the other way around.
Bridge has a dedicated IP.

**NAT** - Your host will act as a router (firewall) and your guests will be on a private subnet. Use this if you are not running servers on the guests.

**Bridged** - Your guests will get a ip address on the same subnet as your host. Use this if you are running servers on the guest and wish to connect from other computers on the LAN.

**Comment by j0nnymoe** [comment]
Ah yea, you're correct. You have opened the port to the correct IP I assume?

**Comment by thewinger** [comment]
Doing `sudo netstat -ntlp | grep LISTEN` inside the docker host (virtualbox guest)
```
tcp6       0      0 :::55651                :::*                    LISTEN      17110/docker-proxy
```

**Comment by thewinger** [comment]
When installing Ubuntu 18.04 in the VM there was an option to install docker at the beginning.

**Comment by j0nnymoe** [comment]
Ah I see, might I suggest you remove the version you have installed and install docker from the official docker repo http://get.docker.com - We've found in the past that our containers can have issues on anything other than that.

**Comment by thewinger** [comment]
Done!
Still port closed :(

**Comment by mil1i** [comment]
I also see this. Now, I don't have any issues with Transmission working. 
But is always shows the port as **Closed**

- Router: Port is open and forwarded to correct server IP
- Host Server: Port is open and listening on the host server
```
docker-pr    4u  IPv6      0t0  TCP *:51413 (LISTEN)
docker-pr    4u  IPv6      0t0  UDP *:51413
---
tcp6       0      0 :::51413                :::*                    LISTEN      -
```
- Container: Port is open and listening inside the container, port passed through on container start
```
tcp        0      0 127.0.0.11:43586        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      -
tcp        0      0 :::51413                :::*                    LISTEN      -
```

```
CentOS Linux release 7.6.1810 (Core) 3.10.0-957.5.1.el7.x86_64
Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01
```

**Comment by PrimozR** [comment]
FYI, had the same issue ad regardless of what I wrote in the settings or in the settings.json file, the listen port was 51413, as defined during installation (followed docker instructions to install docker packages and the smarthomebeginner guide to install the transmission package).
