### ISSUE TITLE
Update to Transmission 2.94 

### ISSUE THREAD

**Issue by razorfrog** [linuxserver/docker-transmission#63]
The image is running Transmission 2.92

Transmission 2.94 was released on May 1 2018
Transmission 2.93 was released on Jan 24 2018

Can we get an update? Thank you!

**Comment by sparklyballs** [comment]
update your image. 

we have been using 2.9.4 since the first friday after the 14th may this year.

```root@Docker-Slave0:/$ [2018-09-25 20:56:55.289] Transmission 2.94
```

test pull of the latest image

**Comment by j0nnymoe** [comment]
![image](https://user-images.githubusercontent.com/10374553/46042850-57b54300-c10e-11e8-86ca-9ab12992407c.png)
Can confirm, image is at 2.94.
