### ISSUE TITLE
UDP Failed

### ISSUE THREAD

**Issue by snowwing** [linuxserver/docker-transmission#64]
If you view the logs you will see the following errors:
```
transmission    | [2018-09-30 16:20:41.770] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
transmission    | [2018-09-30 16:20:41.770] UDP Please add the line "net.core.rmem_max = 4194304" to /etc/sysctl.conf (tr-udp.c:89)
transmission    | [2018-09-30 16:20:41.770] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)
transmission    | [2018-09-30 16:20:41.770] UDP Please add the line "net.core.wmem_max = 1048576" to /etc/sysctl.conf (tr-udp.c:100)
```
Is it worth adding these optimizations?
https://falkhusemann.de/blog/2012/07/transmission-utp-and-udp-buffer-optimizations/

**Comment by hadim** [comment]
@sparklyballs would that be ok to apply [this solution](https://github.com/transmission/transmission/issues/342#issuecomment-397833840) to the Docker image?

**Comment by thelamer** [comment]
These are Kernel parameters you cannot apply these from within Docker. 
You can do these system level on your own servers if you like.

**Comment by pcgeek86** [comment]
If you're on Windows 10 and running Docker Desktop with Windows Subsystem for Linux (WSL), then you want to update `/etc/sysctl.conf` on the Docker Desktop WSL distribution.

1. `wsl --distribution docker-desktop`
2. `vi /etc/sysct.conf`
3. Add lines
4. Restart WSL `wsl --shutdown`
5. Restart Docker Desktop, using the system tray icon
