### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by a10kiloham** [linuxserver/docker-transmission#65]
Is there any reason to keep out python support? I'd like to commit a patch for python as current version has no python support for post processing scripts.

**Comment by thelamer** [comment]
I am putting together a PR to work through all the backlogged issues in this repo, this will be one of them. Will update when it is up for merge.

**Comment by thelamer** [comment]
When this is merged python will be available in the base image: 
https://github.com/linuxserver/docker-transmission/pull/69
