### ISSUE TITLE
Unable to save resume file: permission denied

### ISSUE THREAD

**Issue by willykurmann** [linuxserver/docker-transmission#68]
Transmission frequently stops downloading with the following error:
`Unable to save resume file: permission denied`

Folders in **/config** are set with the following permissions:
![image](https://user-images.githubusercontent.com/496549/52918892-c339c000-32fc-11e9-8b40-785770f98210.png)

I set the **/config/resume** folder permissions to `abc users` and it solved the issue.

Host: Fedora release 29 (Twenty Nine)
Docker: 18.09.1

![image](https://user-images.githubusercontent.com/496549/52919010-f03aa280-32fd-11e9-8a02-713a191b6867.png)

Image linux/transmission was pulled and ran w/o modification

**Comment by thelamer** [comment]
The abc user runs as the UID and GID you pass to it. If you have 1001:1001 perms on a file when you ran with 1000:1000, you must have at some time had a user or container write that file their with 1001:1001 perms.

**Comment by le0pa-RD** [comment]
Same problem here.
But when I look into files permissions resume file has the user permission.

`4 drwsr-xr-x 5 le0pa-rd debian-transmission 4096 Mar 23 12:41 .`
`4 drwxr-xr-x 3 root     root                4096 Mar 23 12:11 ..`
`4 drwxr-xr-x 2 le0pa-rd debian-transmission 4096 Mar 23 12:11 blocklists`
`4 drwxr-xr-x 2 le0pa-rd debian-transmission 4096 Mar 23 12:18 resume`
`0 lrwxrwxrwx 1 le0pa-rd root                  38 Mar 25  2020 settings.json -> /etc/transmission-daemon/settings.json`
`4 -rw------- 1 le0pa-rd debian-transmission  133 Mar 23 12:20 stats.json`
`4 drwxr-xr-x 2 le0pa-rd debian-transmission 4096 Mar 23 12:18 torrents`

Where am I doing wrong?
