### ISSUE TITLE
Unable to customize settings.json at build-time

### ISSUE THREAD

**Issue by RichardMore** [linuxserver/docker-transmission#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	
I am trying to build a customized image with the following Dockerfile content

```
FROM linuxserver/transmission

ARG rpc_username=transmissionuser
ARG rpc_password=transmissionpwd
ARG peer_port=50000

RUN sed -i "/rpc-username/c\    \"rpc-username\": \"${rpc_username}\"," /defaults/settings.json
RUN sed -i "/rpc-password/c\    \"rpc-password\": \"${rpc_password}\"," /defaults/settings.json
RUN sed -i "/peer-port\":/c\    \"peer-port\": ${peer_port}," /defaults/settings.json
```

What I notice after a build is that the /defaults/settings.json will, as it should, contain the modifications, but when starting a docker run or docker-compose up, with the provided arguments, the /config/settings.json will contain none of the edits, except a totally different username that I have not specified anywhere (happens to be the host OS's username).

COPY-ing the final settings.json to /config at build time got replaced as well.

Is there a way to really customize the settings.json at build time?
Is there any use to the /defaults/settings.json?

**Comment by sparklyballs** [comment]
your sed flat out doesn't work , at least for rpc username...
https://pastebin.com/eWN9fkRe

you need to sort that first..

**Comment by RichardMore** [comment]
${rpc_username} and the other ARGs are populated at build time using for example: `--build-arg rpc_username=testuser`

**Comment by sparklyballs** [comment]
works here using a build arg and then running the container. the changes are in /confg/settings.json

the password is hashed but the username is the same..

```
docker build -t --build-arg rpc_username=somerandonnonsense --build-arg rpc_password=randonguff test/test .
```

```cat config/settings.json

{
"alt-speed-down": 50,
"alt-speed-enabled": false,
"alt-speed-time-begin": 540,
"alt-speed-time-day": 127,
"alt-speed-time-enabled": false,
"alt-speed-time-end": 1020,
"alt-speed-up": 50,
"bind-address-ipv4": "0.0.0.0",
"bind-address-ipv6": "::",
"blocklist-enabled": false,
"blocklist-url": "http://www.example.com/blocklist",
"cache-size-mb": 4,
"dht-enabled": true,
"download-dir": "/downloads/complete",
"download-queue-enabled": true,
"download-queue-size": 5,
"encryption": 1,
"idle-seeding-limit": 30,
"idle-seeding-limit-enabled": false,
"incomplete-dir": "/downloads/incomplete",
"incomplete-dir-enabled": true,
"lpd-enabled": false,
"message-level": 2,
"peer-congestion-algorithm": "",
"peer-id-ttl-hours": 6,
"peer-limit-global": 200,
"peer-limit-per-torrent": 50,
"peer-port": 50000,
"peer-port-random-high": 65535,
"peer-port-random-low": 49152,
"peer-port-random-on-start": false,
"peer-socket-tos": "default",
"pex-enabled": true,
"port-forwarding-enabled": true,
"preallocation": 1,
"prefetch-enabled": true,
"queue-stalled-enabled": true,
"queue-stalled-minutes": 30,
"ratio-limit": 2,
"ratio-limit-enabled": false,
"rename-partial-files": true,
"rpc-authentication-required": false,
"rpc-bind-address": "0.0.0.0",
"rpc-enabled": true,
"rpc-host-whitelist": "",
"rpc-host-whitelist-enabled": true,
"rpc-password": "{b0537edf8120dd3f003c815a8d4d24d2c1abea66EzazEmNk",
"rpc-port": 9091,
"rpc-url": "/transmission/",
"rpc-username": "somerandonnonsense",
"rpc-whitelist": "127.0.0.1",
"rpc-whitelist-enabled": false,
"scrape-paused-torrents-enabled": true,
"script-torrent-done-enabled": false,
"script-torrent-done-filename": "",
"seed-queue-enabled": false,
"seed-queue-size": 10,
"speed-limit-down": 100,
"speed-limit-down-enabled": false,
"speed-limit-up": 100,
"speed-limit-up-enabled": false,
"start-added-torrents": true,
"trash-original-torrent-files": false,
"umask": 2,
"upload-slots-per-torrent": 14,
"utp-enabled": true,
"watch-dir": "/watch",
"watch-dir-enabled": true
}

```

**Comment by sparklyballs** [comment]
these modifications however fall outside the scope of support for the image as it works as provided.

**Comment by RichardMore** [comment]
It seems as you showed it that it works in this scenario.
I created one, where I am using docker-compose for easy commands, and the first "plain" one seems to work normally, but in the second where I do an additional step of replacing the original web UI with a different one, the config won't be the same and the issue is present then.

Can you help me figure out why in this case it will act differently?

[Here is the pastebin for the whole command chain and results](https://pastebin.com/a2hKuddy)

**Comment by thelamer** [comment]
Don't talk in dead issues. 
And we provide env variables to use a custom ui . 
Read the readme completely you don't need to do any of that stuff.

We will never directly support modifying our base images.
