### ISSUE TITLE
memory leaking?

### ISSUE THREAD

**Issue by dedmo** [linuxserver/docker-transmission#77]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Synology NAS, DSM 6.2.2-24922 (INTEL Atom C2538)

[linuxserver-transmission.zip](https://github.com/linuxserver/docker-transmission/files/3351849/linuxserver-transmission.zip)

The last several versions of the linuxserver docker/transmission require a lot of RAM and slow down terribly. After restarting the container, 1-2 days work fine, then repeats. Also found that an additional process transmission-daemon is being added every day. This is normal?

![linuxserver RAM leaking](https://user-images.githubusercontent.com/35141603/60538289-011b0c00-9d13-11e9-8e0c-07ce48a02f54.JPG)

**Comment by jkaberg** [comment]
My bet: https://github.com/linuxserver/docker-transmission/blob/master/root/defaults/blocklist-update.sh

@thelamer thoughts?

**Comment by dedmo** [comment]
@jkaberg, Yes I'm use blocklist. Sorry, can't comment script, I'm simple user :-|
Since 3 Jul i'm test linuxserver/transmission with disabled UDP. It looks like the RAM usage has decreased. Please see attached screenshot with total system RAM usage for last month.

But additional background process "transmission-daemon" continues to be added. Jul 3 - 1 process "transmission-daemon", today 5 Jul - 4 process.

![synology RAM usage log](https://user-images.githubusercontent.com/35141603/60705472-e2ce2f80-9f0f-11e9-9ded-0bea0c73e0f1.png)

**Comment by jkaberg** [comment]
@dedmo Unless I read this completely wrong the blocklist script will launch a new instance of transmission each time its run (which is everyday according to the README)

Interesting take on UDP, will keep that in mind

**Comment by jkaberg** [comment]
Based on the Transmission documentation the blocklist script should do something like this instead:

```SID=$(curl -sSLI http://localhost:9091/transmission/ | grep -Fi X-Transmission-Session-Id | cut -d ' ' -f 2) curl -sSL http://localhost:9091/transmission/rpc -H "X-Transmission-Session-Id: $SID" -d '{\"method\":\"blocklist-update\",\"arguments\":{},\"tag\":\"\"}'```

The above is not tested. This should replace the current restart method as thats unnecessary.

**Comment by dedmo** [comment]
@jkaberg 
Thanks for your time. Now I set "blocklist-enabled": false. I'm check it after few days and leave a comment here (if needed).
Do I understand correctly that sometime in the next versions the blocklist script may be fixed?

**Comment by sparklyballs** [comment]
@jkaberg that doesn't take into account that someone may be using a password

**Comment by jkaberg** [comment]
@sparklyballs just parse the settings.json file?

**Comment by dedmo** [comment]
> @jkaberg
> Thanks for your time. Now I set "blocklist-enabled": false. I'm check it after few days and leave a comment here (if needed).

In my case:
1) utp-enabled: false - normalize RAM use and system
2) blocklist-enabled: false - background process "transmission-daemo" no longer multiplies each days

**Comment by thelamer** [comment]
Closing pending https://github.com/linuxserver/docker-transmission/pull/78

**Comment by dedmo** [comment]
Unfortunatelly multiply pocess issue not solved. See screenshot below (latest version linuxserver/transmission)
![Снимок](https://user-images.githubusercontent.com/35141603/61636650-b4d24480-ac9e-11e9-8a97-960f0783dae0.JPG)

**Comment by thelamer** [comment]
@dedmo post logs and also execute into the container and run : 
```
s6-svc -t /var/run/s6/services/transmission
```

This is the output you should get: 
```
Caught SIGTERM signal!
localhost:9091/transmission/rpc/ responded: "success"
[2019-07-22 16:18:58.850] Saved "/config/settings.json" (variant.c:1266)
[2019-07-22 16:18:58.850] DHT Not saving nodes, DHT not ready (tr-dht.c:359)
[2019-07-22 16:18:58.850] Port Forwarding Stopped (port-forwarding.c:180)
Closing transmission session... done.
```

Then s6 will pickup and start the app as it detects the down pid.

**Comment by thelamer** [comment]
NM I see what is wrong, you need to delete the existing blocklis-update script in /config and restart the container. 
https://github.com/linuxserver/docker-transmission/blob/master/root/etc/cont-init.d/20-config#L11-L13

The assumption is that people are customizing this script.

**Comment by dedmo** [comment]
@thelamer 
log file attached.
[linuxserver-transmission2.zip](https://github.com/linuxserver/docker-transmission/files/3418790/linuxserver-transmission2.zip)
Now I see six background process.

**Comment by dedmo** [comment]
> 
> 
> NM I see what is wrong, you need to delete the existing blocklis-update script in /config and restart the container.
> https://github.com/linuxserver/docker-transmission/blob/master/root/etc/cont-init.d/20-config#L11-L13
> 
> The assumption is that people are customizing this script.

Unfortunatylly steps:
- stop container
- delete "blocklist-update.sh" in "/config" 
- run contaiter 
don't solve problem - process "transmission-daemon" still multiply.
![Снимок](https://user-images.githubusercontent.com/35141603/61891325-1a7a3700-af12-11e9-96ae-4bf4ae72fa49.JPG)
