### ISSUE TITLE
Why doesn't it download without an interactive terminal?

### ISSUE THREAD

**Issue by jayavanth** [linuxserver/docker-transmission#79]
When I run docker-transmission with:
`docker run -it linuxserver/docker-transmission /bin/bash`
and then start a download like this

`transmission-remote -a "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969"`

It works fine!

But, when I run it non-interactively:

`docker run linuxserver/docker-transmission transmission-remote -a "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969"`

I get this error: [error log](https://pastebin.com/t5azkVt1)

What am I doing wrong?

Host OS:
Ubuntu 18.04

**Comment by tobbenb** [comment]
See the Readme for how to set it up correctly.
