### ISSUE TITLE
Securing with Username/Password

### ISSUE THREAD

**Issue by benbristow** [linuxserver/docker-transmission#8]
Hey,

I'm loving your container images, but just a problem with this one.

I was previously using dperson's Transmission image which allows you to provide a username/password for Transmission, but this image doesn't seem to have one.
https://hub.docker.com/r/dperson/transmission/

Any chance of seeing this incorporated?

- Ben.

**Comment by zaggash** [comment]
Hello,

Do these things in the exact order:

Shutdown: /etc/init.d/transmission-daemon stop
Write the rpc-password in the /etc/transmission-daemon/settings.json file, in double-quotes.
Save that file
Startup: /etc/init.d/transmission-daemon start
Login to the page, it's at port 9091
Type in your password.
The password that's being overwritten is a hash. The program is smarter than usual and detects that your password is not a hash, so it overwrites the password with the hash to be secure. So your password should work.

**Comment by sparklyballs** [comment]
would add to this...

you need to change/check the following settings in the json file also.

"rpc-authentication-required": true,
"rpc-username": "transmission",

+ substituting transmission above for your chosen user name. (use double quotes)

**Comment by freshjewbagel** [comment]
How do I do that in my docker compose file? This does not work, keeps saying I need to set a user/pass:

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    env_file:
      - 'variables.env'
    restart: always
    ports:
    - "9091:9091"
    volumes:
      - ${USERDIR}/docker/shared:/shared
      - ${USERDIR}/Downloads:/data/watch
      - ${USERDIR}/Downloads/completed:/data/completed
      - ${USERDIR}/Downloads/incomplete:/data/incomplete
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - rpc-authentication-required=true
      - rpc-username="transmission"
      - rpc-password="transmission"

**Comment by fredfred41** [comment]
hi, did you managed to set up the compose file right? I m not able to make it work?
Thanks

**Comment by zaggash** [comment]
There is nothing to do with the compose file.
It is all in the config file.
