### ISSUE TITLE
Include Avahi for easy discovery

### ISSUE THREAD

**Issue by erwan** [linuxserver/docker-transmission#86]
It would be nice to have Avahi running in the container, so it can be accessed locally using a domain in `.local`.

Even better would be to have a redirect from port `80` (maybe with a uhttpd server) so we don't have to remember that transmission runs on port `9091`.

##  Expected Behavior
Being able to access Transmission with `http://transmission.local:9091` (or even better `http://transmission.local`)

## Current Behavior
I have to access Transmission with `http://192.168.1.42:9091`

I could try a PR but is it something you would likely accept?

**Comment by aptalca** [comment]
If you want to access it at port 80, you can easily map it to port 80 `-p 80:9091`

If you want to access it with pretty urls, you can set up an nginx reverse proxy.

Adding avahi to the container has little benefit but potential issues as it clashes with other instances on the host or other containers
