### ISSUE TITLE
port closed using second ip

### ISSUE THREAD

**Issue by ZackEndboss** [linuxserver/docker-transmission#88]
## Expected Behavior
I want to bind the peer-port on a second ip (-p ip2:51413:51413 & udp )

## Current Behavior
The peer-port (not ui) are always closed if i specify the second ip. (ip1 works) (checked with trans port test - and as result by tracker)

## Steps to Reproduce
create a container of this image with second or not main ip (not sure about the technically correct description)

## Environment
**OS:** debian 10      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Command used to create docker container
**Port open (all fine)**
docker create \
  --name=transmission \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ='Europe/Berlin' \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v /home/user/log:/log \
  -v /home/user/config:/config \
  -v /home/user/Downloads:/downloads \
  linuxserver/transmission

**Port closed (not working)**
docker create \
  --name=transmission \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ='Europe/Berlin' \
  -p ip2:9091:9091 \
  -p ip2:51413:51413 \
  -p ip2:51413:51413/udp \
  -v /home/user/log:/log \
  -v /home/user/config:/config \
  -v /home/user/Downloads:/downloads \
  linuxserver/transmission

**Test: Port open (all fine - browser testpage)**
docker run -d -p ip2:51413:80 tutum/apache-php

## Addition Infos
- some other interesting fact: the ui is available at ip2.
- i also tried some diff ports to exclude 51413-Issues
- all tests are done remote (home-client -> remote-root-server)
- without docker, ip2 works fine with transmission (configured as "bind-address-ipv4" in settings.json [of course not configured while using docker])

netstat -tuplen | grep 51413 # looks good
tcp        0      0 ip2:51413        0.0.0.0:*               LISTEN      0          3239823    7307/docker-proxy
udp        0      0 ip2:51413        0.0.0.0:*                           0          3244174    7321/docker-proxy

## ideas 
There is something with the "bind-address-ipv4" or the "peer-port" logic that does not work with with docker-mapped ips

**Comment by ZackEndboss** [comment]
ok - I have been thinking how the docker-mapping works
fact: the ip for outgoing-calls is always the main-ip of the host-system if nothing else is defined -and-
listening on binded ip:port, if I understand correctly, does not change this fact.
The question is now: how could the service inside the container use another ip, he doesnt know, to send requests.
The "bind-address-ipv4" could not handle this special routing-case if im right. 
At the end the only solution i come to, is to define some iptable rules - isn't it?
At least until there is a "--outgoing-ip" implementation for docker.

**Comment by ZackEndboss** [comment]
A small script-snipped to create outgoing iptable rule for specific container.
Not the best solution - each "docker create" random assigned ip addresses.
Probably a docker network is a better way but not in may case. (lack of communication with other container)
Hopefully there will be an argument as docker-parameter (like: --outgoing-ip=...) in the future. For now it is only an intensely discussed topic. 
```
#!/bin/bash

SourceIP=ip2 # Outgoing IP to use
# Gets IP of last launched docker container
CID="container-name"
# Gets custom network of docker container
NETMAP=$(docker inspect --format '{{ .HostConfig.NetworkMode }}' $CID)
if [ "$NETMAP" == "default" ]; then NETMAP="bridge"; fi
# Gets ip address of container
IPADDR=$(docker inspect --format "{{ .NetworkSettings.Networks.$NETMAP.IPAddress }}" $CID)
# Sets up SNAT iptables rule for docker container to use SourceIP for outgoing traffic
iptables -t nat -I POSTROUTING -p all -s $IPADDR -j SNAT --to $SourceIP
# Remove iptable rule
#iptables -t nat -D POSTROUTING -p all -s $IPADDR -j SNAT --to $SourceIP
# List all
#iptables -t nat -L"
```

**Comment by thelamer** [comment]
there is nothing we can change in our containers logic to support this without telling people to run privileged container flags and custom iptables rules. 

As such I will be closing this case, and I wish you luck with your setup. Also this might be helpful to keep your local logic persistent https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
