### ISSUE TITLE
Environment variables not working

### ISSUE THREAD

**Issue by bonovski** [linuxserver/docker-transmission#90]
environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      - USER=username #optional
      - PASS=password #optional

1. PUID and PGID are not working, had to chown the folder as it was created as root.

2. USER and PASS are not working. 
Is this for the webgui at all?
The documentation then further down says to change it in the settings.json

> 
> Securing the webui with a username/password.
> this requires 3 settings to be changed in the settings.json file.
> 
> Make sure the container is stopped before editing these settings.
> 
> "rpc-authentication-required": true, - check this, the default is false, change to true.
> 
> "rpc-username": "transmission", substitute transmission for your chosen user name, this is just an example.
> 
> rpc-password will be a hash starting with {, replace everything including the { with your chosen password, keeping the quotes.
> 
> Transmission will convert it to a hash when you restart the container after making the above edits.
> 
>

**Comment by tobbenb** [comment]
1. PUID and PGID are working. You do not mention which folder you chown yourself.

2. What does your settings.json file say about username and password after setting the variables?

3. Please provide all information we ask about in the issue template. Posting just a selected part is not helpful.

**Comment by bonovski** [comment]
Well everything works fine now, I deleted the whole container, all folders and files and it works as it should. Seems like some docker-compose stuff didn't reset itself how it should.
