### ISSUE TITLE
Can't "remove and delete"

### ISSUE THREAD

**Issue by nelsonblaha** [linuxserver/docker-transmission#93]
## Expected Behavior
Seeded files should be deleted when "remove and delete data" is chosen in Transmission Remote

## Current Behavior
Torrent is removed and paused but data is not deleted

## Steps to Reproduce
1. Bind a writeable location to the container (observed /media/ssda/sonarr/seeding not working)
2. Download a torrent and begin seeding
3. Choose "remove and delete data" on the torrent

## Environment
**OS:** Ubuntu 18.04 (server and client, client using Transmission Remote 1.3.1)
**CPU architecture:** x86_64
**How docker service was installed:** Portainer

## Command used to create docker container (run/create/compose/screenshot)
```docker run --name transmission --runtime runc -v /media/ssda/docker_volumes/transmission/config:/config -v /media/ssda:/media/ssda -v /media/nelnet/seeds:/downloads -v /media/ssda/lidarr:/media/ssda/lidarr -v /media/nelnet:/media/nelnet -v /media/ssda/docker_volumes/transmission/watch:/watch -v /media/drobo:/media/drobo -v /media/ssda/docker_volumes/transmission/postscript:/postscript -p 51413:51413/tcp -p 51413:51413/udp -p 9091:9091/tcp --net bridge --restart unless-stopped -h 7f1539fa72c4 --expose 51413/tcp --expose 51413/udp --expose 9091/tcp -e 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' -e 'PS1=$(whoami)@$(hostname):$(pwd)\$ ' -e 'HOME=/root' -e 'TERM=xterm' -e 'PUID=1000' -e 'PGID=1000' -e 'TZ=US/Central' -e 'USER=ben' -e 'PASS=foobar' -d --entrypoint "/init" linuxserver/transmission:latest```

## Docker logs
```[2020-01-12 18:04:52.403] My.Torrent Removing torrent (torrent.c:1915)
[2020-01-12 18:04:52.403] My.Torrent Pausing (torrent.c:1856)

```

**Comment by thelamer** [comment]
You got some perm problems This functionality works fine on a local test. 
Please use this exact torrent first as a loop test: 
http://releases.ubuntu.com/18.04.3/ubuntu-18.04.3-desktop-amd64.iso.torrent

The pause message from a log standpoint is what is expected. 

The easiest way to see if it is your volume mounted for downloads is to not mount a colume for downloads and just loop test this locally using something like: 
```
docker run --rm -it -p 51413:51413/tcp -p 51413:51413/udp -p 9091:9091/tcp linuxserver/transmission bash
```

Hop in the webui on 9091 add the torrent, delete the torrent and files, then run `ls -l /downloads/complete` to see if the file is still there. I am confident it will not be. 

In any case this is not the platform for support so I will be closing this issue.
