### ISSUE TITLE
[Feature Request] Add reverse proxy for ssl

### ISSUE THREAD

**Issue by augustozanellato** [linuxserver/docker-transmission#96]
Would you mind adding a possibility to have an integrated reverse proxy in order to support HTTPS connections to the container?

**Comment by aptalca** [comment]
We recommend an external reverse proxy. See our letsencrypt solution here: https://github.com/linuxserver/docker-letsencrypt

And here's a guide: https://blog.linuxserver.io/2019/04/25/letsencrypt-nginx-starter-guide/
