### ISSUE TITLE
Multi daemon spawned on blocklist refresh when authentication is enabled

### ISSUE THREAD

**Issue by YouriT** [linuxserver/docker-transmission#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

There shouldn't be multiple daemons running at the same time

## Current Behavior

At night, when `blocklist-update.sh` script is being executed, a new daemon is spawned but the old one never dies.

As we can see in the logs, the issue occurs because on SIGTERM being sent to the daemon, where the authentication is missing.

## Steps to Reproduce

1. In transmission config, enable rpc-auth with username and password
```json
...
"blocklist-enabled": true,
"blocklist-url": "http://john.bitsurge.net/public/biglist.p2p.gz",
...
"rpc-authentication-required": true,
"rpc-bind-address": "0.0.0.0",
"rpc-enabled": true,
"rpc-password": "some-password",
"rpc-port": 9091,
"rpc-url": "/transmission/",
"rpc-username": "some-username",
"rpc-whitelist": "127.0.0.1",
"rpc-whitelist-enabled": false,
...
```
2. Shell into the running container
3. Execute `blocklist-update.sh`
4. `ps -a` shows now 2 running daemons

## Environment
**OS:**      Linux Ubuntu
**CPU architecture:** x86_64
**How docker service was installed:**      Apt
**linuxserver/transmission image SHA:** 7465b15bcd1f

## Command used to create docker container (run/create/compose/screenshot)

docker-compose.yml
```
version: '3'
services:
  transmission:
    image: linuxserver/transmission
    restart: unless-stopped
    ports:
      - 55032:55032/udp
      - 55032:55032
    environment:
      - TZ=Europe/Brussels
      - PUID=10000
      - PGID=10000
    volumes:
      - ./transmission-settings.json:/config/settings.json:ro
      - /storage:/downloads
      - transmission-config:/config
```

```shell
$ docker-compose up -d
```

## Docker logs

```
transmission_1  | Caught SIGTERM signal!
transmission_1  | Unexpected response: <h1>401: Unauthorized</h1>Unauthorized User
transmission_1  | [cont-finish.d] executing container finish scripts...
transmission_1  | [cont-finish.d] done.
transmission_1  | [s6-finish] waiting for services.
transmission_1  | [s6-finish] sending all processes the TERM signal.
transmission_1  | [2020-03-17 00:39:18.808] Reloading settings from "/config" (daemon.c:472)
transmission_1  | [2020-03-17 00:39:18.808] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
transmission_1  | [2020-03-17 00:39:18.808] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
transmission_1  | [2020-03-17 00:39:18.808] RPC Server Password required (rpc-server.c:1220)
transmission_1  | [2020-03-17 00:39:18.808] Port Forwarding Stopped (port-forwarding.c:180)
transmission_1  | [2020-03-17 00:39:18.900] Reloading settings from "/config" (daemon.c:472)
transmission_1  | [2020-03-17 00:39:18.900] RPC Server Adding address to whitelist: 127.0.0.1 (rpc-server.c:971)
transmission_1  | [2020-03-17 00:39:18.900] RPC Server Serving RPC and Web requests on port 127.0.0.1:9091/transmission/ (rpc-server.c:1213)
transmission_1  | [2020-03-17 00:39:18.900] RPC Server Password required (rpc-server.c:1220)
transmission_1  | [2020-03-17 00:39:18.900] Couldn't bind port 55032 on 0.0.0.0: Address in use (Is another copy of Transmission already running?) (net.c:379)
transmission_1  | [2020-03-17 00:39:18.901] Couldn't bind port 55032 on ::: Address in use (Is another copy of Transmission already running?) (net.c:379)
```

**Comment by drizuid** [comment]
I'm able to reproduce this
https://pastebin.com/vbDqRLQU

```
root@cba4ebe7e64c:/config# ps -a
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   34 root      0:00 s6-supervise s6-fdholderd
  248 root      0:00 s6-supervise transmission
  250 root      0:00 s6-supervise cron
  252 root      0:00 bash ./run
  253 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
  258 abc       0:06 /usr/bin/transmission-daemon -g /config -c /watch -f
  322 root      0:00 /bin/bash
  336 root      0:00 ps -a
root@cba4ebe7e64c:/config# ./blocklist-update.sh
root@cba4ebe7e64c:/config# ps -a
PID   USER     TIME  COMMAND
    1 root      0:00 s6-svscan -t0 /var/run/s6/services
   34 root      0:00 s6-supervise s6-fdholderd
  248 root      0:00 s6-supervise transmission
  250 root      0:00 s6-supervise cron
  253 root      0:00 /usr/sbin/crond -f -S -l 0 -c /etc/crontabs
  258 abc       0:10 /usr/bin/transmission-daemon -g /config -c /watch -f
  322 root      0:00 /bin/bash
  360 root      0:00 bash ./run
  362 abc       0:04 /usr/bin/transmission-daemon -g /config -c /watch -f
  416 root      0:00 ps -a
```

Something to add to this is that if you add a blocklist through the web gui, it will load it, but settings.json doesn't update. Because of the way blocklist-update.sh works, this means that the blocklist will never update.

**Comment by aptalca** [comment]
In order for transmission to be stopped cleanly, we need to use the user pass if auth is enabled, therefore the user pass needs to be set via the env vars `USER` & `PASS` in compose (or docker run).

If you manually set auth, our service will not be able to bring it down, resulting in launching a second instance: https://github.com/linuxserver/docker-transmission/blob/master/root/etc/services.d/transmission/run#L5-L10

This was implemented a while back but we missed an update to the readme.

**Comment by YouriT** [comment]
Makes much sense @aptalca thanks for updating the docs!
